---
- name: Install Java 11
  hosts: all
  become: yes
  tasks:
    - name: Install Java 11 on CentOS
      yum:
        name: java-11-openjdk
        state: present
      when: "'CentOS' in ansible_distribution"

    - name: Install Java 11 on Ubuntu
      apt:
        name: openjdk-11-jdk
        state: present
      when: "'ubuntu' in ansible_distribution"
      register: install_result

    - debug:
        var: install_result
      when: install_result.failed

    - name: Set Java 11 as the default Java version (CentOS)
      command: alternatives --install /usr/bin/java java /usr/lib/jvm/java-11-openjdk-{{ ansible_architecture }}/bin/java 1
      args:
        creates: /usr/bin/java
      when: "'CentOS' in ansible_distribution"

    - name: Set JAVA_HOME environment variable
      set_fact:
        java_home_path: "/usr/lib/jvm/java-11-openjdk-{{ ansible_architecture }}"
      when: "'CentOS' in ansible_distribution or 'Ubuntu' in ansible_distribution"

    - name: Display Java version
      command: java -version

    - name: Print JAVA_HOME path
      debug:
        var: java_home_path
...