---
- name: Install Java 11 on CentOS
  hosts: n5c
  become: yes

  tasks:
    - name: Install Java 11
      yum:
        name:
          - java-11-openjdk
        state: present
      when: "'CentOS' in ansible_distribution"

    - name: Set Java 11 as the default Java version (CentOS)
      command: alternatives --install /usr/bin/java java /usr/lib/jvm/java-11-openjdk-<arch>/bin/java 1
      args:
        creates: /usr/bin/java
      when: "'CentOS' in ansible_distribution"

    - name: Display Java version
      command: java -version
...
