- name: Install Java 11
  hosts: n4c
  become: true
  tasks:
    - name: Install EPEL repository on CentOS
      ansible.builtin.yum:
        name: epel-release
        state: present
      when: "'CentOS' in ansible_distribution"

    - name: Install Java 11 on CentOS
      ansible.builtin.yum:
        name: java-11-openjdk
        state: present
        enablerepo: epel
      when: "'CentOS' in ansible_distribution"

    - name: Install Java 11 on Amazon Linux
      ansible.builtin.dnf:
        name: java-11-amazon-corretto
        state: present
      when: "'Amazon' in ansible_distribution"

    - name: Install Java 11 on Ubuntu
      ansible.builtin.apt:
        name: openjdk-11-jdk
        state: present
      when: "'Ubuntu' in ansible_distribution"

    - name: Set Java 11 as the default on CentOS
      ansible.builtin.alternatives:
        name: java
        path: /usr/lib/jvm/java-11-openjdk-<your-specific-version>/bin/java
        state: present
      when: "'CentOS' in ansible_distribution"

    - name: Set Java 11 as the default on Amazon Linux
      ansible.builtin.alternatives:
        name: java
        path: /usr/lib/jvm/java-11-amazon-corretto/bin/java
        state: present
      when: "'Amazon' in ansible_distribution"

    - name: Set Java 11 as the default on Ubuntu
      ansible.builtin.update_alternatives:
        name: java
        path: /usr/lib/jvm/java-11-openjdk-<your-specific-version>/bin/java
        state: present
      when: "'Ubuntu' in ansible_distribution"

    - name: Display Java Version and Path
      ansible.builtin.shell:
        cmd: |
          java -version
          echo "Java Home: $(dirname $(dirname $(readlink -f $(which java))))"
      register: java_info

    - name: Display Java Info
      ansible.builtin.debug:
        var: java_info.stdout_lines
...