---
- name: Install Java
  hosts: all
  become: true
  tasks:
    - name: Update package lists (for Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install Python 3 (for CentOS)
      raw: sudo yum install -y python3
      when: ansible_os_family == 'RedHat'

    - name: Update package lists (for CentOS and Amazon Linux)
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'

    - name: Install OpenJDK 11
      package:
        name: openjdk-11-jdk
        state: present
      when: ansible_os_family == 'Debian'  # For Ubuntu

    - name: Install OpenJDK 11
      package:
        name: java-11-openjdk
        state: present
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '8'  # For CentOS 8 and Amazon Linux 2

    - name: Install Java on CentOS
      package:
        name: java
        state: present
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'

    - name: Print Java version
      command: java -version
      register: java_version
      ignore_errors: yes  # Ignore errors if the 'java' command is not found

    - debug:
        var: java_version.stdout_lines

    - name: Debug - Installation failed
      debug:
        msg: "Java installation failed"
      when: java_version.failed
...