---
- name: Install Java 11
  hosts: all
  become: true
  tasks:
    - name: Install Java 11 on CentOS
      ansible.builtin.yum:
        name: java-11-openjdk
        state: present
        enablerepo: epel
      when: "'CentOS' in ansible_distribution"

    - name: Install Java 11 on Amazon Linux
      ansible.builtin.yum:
        name: java-11-openjdk
        state: present
      when: "'Amazon' in ansible_distribution"

    - name: Install Java 11 on Ubuntu
      ansible.builtin.apt:
        name: openjdk-11-jdk
        state: present
      when: "'Ubuntu' in ansible_distribution"
...