---
- name: Build and Package with Maven on Jenkins Slave
  hosts: n4c
  tasks:
    - name: Ensure ~/ansibleproject directory is absent
      file:
        path: "~/ansibleproject"
        state: absent

    - name: Create project directory
      file:
        path: "~/ansibleproject"
        state: directory

    - name: Clone Git repository (if needed)
      git:
        repo: "https://github.com/titilopem/JavaWebAnsible.git"
        dest: "~/ansibleproject"

    - name: Build Maven project
      command: "mvn clean package"
      args:
        chdir: "~/ansibleproject"
...
