---
- name: Manage Apache Tomcat
  hosts: group1
  become: yes

  tasks:
    - name: Install necessary packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - java
        - tar
      when: ansible_os_family == "Debian"

    - name: Install necessary packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - java-1.8.0-openjdk
        - tar
      when: ansible_os_family == "RedHat"

    - name: Create Tomcat group
      ansible.builtin.group:
        name: tomcat

    - name: Create Tomcat user
      ansible.builtin.user:
        name: tomcat
        group: tomcat
        home: /opt/tomcat
        shell: /bin/nologin

    - name: Download Apache Tomcat
      ansible.builtin.get_url:
        url: "https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.72/bin/apache-tomcat-8.5.72.tar.gz"
        dest: /tmp/apache-tomcat-8.5.72.tar.gz

    - name: Extract Apache Tomcat
      ansible.builtin.unarchive:
        src: /tmp/apache-tomcat-8.5.72.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Ensure Tomcat scripts are present
      ansible.builtin.stat:
        path: /opt/tomcat/bin/{{ item }}
      loop:
        - shutdown.sh
        - startup.sh
      register: tomcat_scripts

    - name: Download Tomcat scripts if not present
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/apache/tomcat/master/bin/{{ item.item }}"
        dest: "/opt/tomcat/bin/{{ item.item }}"
      when: not item.stat.exists
      loop: "{{ tomcat_scripts.results }}"

    - name: Set ownership and permissions for Tomcat directory
      ansible.builtin.file:
        path: /opt/tomcat
        state: directory
        owner: tomcat
        group: tomcat
        recurse: yes

    - name: Set executable permissions for Tomcat scripts
      ansible.builtin.file:
        path: /opt/tomcat/bin
        state: directory
        recurse: yes
        mode: '0755'

    - name: Set ownership and permissions for Tomcat scripts
      ansible.builtin.file:
        path: /opt/tomcat/bin
        state: directory
        owner: tomcat
        group: tomcat
        recurse: yes

    - name: Configure Tomcat systemd service
      ansible.builtin.copy:
        dest: /etc/systemd/system/tomcat.service
        content: |
          [Unit]
          Description=Apache Tomcat Web Application Container
          After=syslog.target network.target

          [Service]
          Type=forking
          Environment=JAVA_HOME=/usr/lib/jvm/default-java
          Environment=CATALINA_PID=/opt/tomcat/temp/tomcat.pid
          Environment=CATALINA_HOME=/opt/tomcat
          Environment=CATALINA_BASE=/opt/tomcat
          Environment='CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC'
          Environment='JAVA_OPTS=-Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom'

          ExecStart=/opt/tomcat/bin/startup.sh
          ExecStop=/opt/tomcat/bin/shutdown.sh

          User=tomcat
          Group=tomcat
          UMask=0007
          RestartSec=10
          Restart=always

          [Install]
          WantedBy=multi-user.target

      notify: Reload Tomcat

  handlers:
    - name: Reload Tomcat
      ansible.builtin.systemd:
        name: tomcat
        state: restarted
...