- name: Manage Apache Tomcat
  hosts: group1
  become: true

  tasks:
    - name: Set JAVA_HOME
      ansible.builtin.set_fact:
        java_home_path: "/usr/lib/jvm/java-11-openjdk-amd64"

    - name: Set environment variables
      ansible.builtin.lineinfile:
        path: "/etc/environment"
        line: "JAVA_HOME={{ java_home_path }}"
        create: yes

    - name: Set Tomcat service name based on distribution
      ansible.builtin.set_fact:
        tomcat_service_name: >-
          {%- if ansible_distribution in ['Ubuntu', 'Debian'] -%}
          tomcat8
          {%- else -%}
          tomcat
          {%- endif -%}

    - name: Reload systemd
      ansible.builtin.command: "systemctl daemon-reload"

    - name: Shutdown Tomcat service if running
      ansible.builtin.shell: "/bin/bash -c 'source /etc/environment && /opt/{{ tomcat_service_name }}/bin/shutdown.sh'"
      ignore_errors: yes  # Ignoring errors if script is not found or service not running

    - name: Check if shutdown.sh exists
      ansible.builtin.stat:
        path: "/opt/{{ tomcat_service_name }}/bin/shutdown.sh"
      register: shutdown_script

    - name: Start Tomcat service if shutdown.sh exists
      ansible.builtin.shell: "/bin/bash -c 'source /etc/environment && /opt/{{ tomcat_service_name }}/bin/startup.sh'"
      ignore_errors: yes  # Ignoring errors if script is not found or service not running
      when: shutdown_script.stat.exists
...