---
- name: Test WebApp with Maven and Stash
  hosts: n4c
  become: true

  tasks:
    - name: Test the webapp using Maven
      command: "mvn test"

    # - name: Stash the build artifacts
    #   stash:
    #     name: webapp-artifacts
    #     path: "~/target/"
...
