# Manage Apache Tomcat
---
- name: Manage Apache Tomcat
  hosts: group1
  become: true

  tasks:
    - name: Download Apache Tomcat
      ansible.builtin.get_url:
        url: "https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.72/bin/apache-tomcat-8.5.72.tar.gz"
        dest: "/tmp/apache-tomcat-8.5.72.tar.gz"

    - name: Extract Apache Tomcat
      ansible.builtin.unarchive:
        src: "/tmp/apache-tomcat-8.5.72.tar.gz"
        dest: "/opt/"
        remote_src: yes

    - name: Set JAVA_HOME
      ansible.builtin.set_fact:
        java_home_path: "/usr/lib/jvm/java-11-openjdk-amd64"

    - name: Set environment variables
      ansible.builtin.lineinfile:
        path: "/etc/environment"
        line: "JAVA_HOME={{ java_home_path }}"
        create: yes

    - name: Set Tomcat service name based on distribution
      ansible.builtin.set_fact:
        tomcat_service_name: >-
          {%- if ansible_distribution in ['Ubuntu', 'Debian'] -%}
          tomcat8
          {%- else -%}
          tomcat
          {%- endif -%}

    - name: Reload systemd
      ansible.builtin.command: "systemctl daemon-reload"

    - name: Shutdown Tomcat service
      ansible.builtin.command: "/bin/bash -c 'source /etc/environment && /opt/tomcat/bin/shutdown.sh'"
      ignore_errors: yes  # Ignoring errors as the service might not be running

    - name: Start Tomcat service
      ansible.builtin.command: "/opt/tomcat/bin/startup.sh"
      args:
        creates: "/opt/tomcat/bin/startup.sh"  # Skip if the service is already running
...