---
- name: Install Java 11
  hosts: group1
  become: yes
  tasks:
    - name: Install Java 11 on CentOS
      yum:
        name: java-11-openjdk
        state: present
      when: "'CentOS' in ansible_distribution"

    - name: Install Java 11 on Ubuntu
      apt:
        name: openjdk-11-jdk
        state: present
      when: "'Ubuntu' in ansible_distribution"

    - name: Set Java 11 as the default Java version (CentOS)
      command: alternatives --install /usr/bin/java java /usr/lib/jvm/java-11-openjdk-{{ ansible_architecture }}/bin/java 1
      args:
        creates: /usr/bin/java
      when: "'CentOS' in ansible_distribution"

    - name: Display Java version
      command: java -version

- name: Install Apache Tomcat
  hosts: group1
  become: true
  tasks:
    - name: Check the OS Distribution
      debug:
        var: ansible_distribution

    - name: Update package cache on Ubuntu
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Update package cache on CentOS
      yum:
        update_cache: yes
      when: ansible_distribution == "CentOS"

    - name: Install default available Java on Ubuntu
      apt:
        name: default-jdk
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Install OpenJDK on CentOS
      yum:
        name: java-11-openjdk
        state: present
      when: ansible_distribution == "CentOS"

    - name: Install wget
      package:
        name: wget
      when: ansible_distribution in ['Ubuntu', 'CentOS']

    - name: Create a directory for Tomcat installation
      file:
        path: /opt
        state: directory

    - name: Download Apache Tomcat
      ansible.builtin.get_url:
        url: "https://downloads.apache.org/tomcat/tomcat-10/v10.1.16/bin/apache-tomcat-10.1.16.tar.gz"
        dest: "/tmp/apache-tomcat-10.1.16.tar.gz"

    - name: Extract Tomcat archive
      ansible.builtin.unarchive:
        src: "/tmp/apache-tomcat-10.1.16.tar.gz"
        dest: "/opt"
        remote_src: yes

    - name: Set Tomcat environment variables
      lineinfile:
        path: "/etc/environment"
        line: "export CATALINA_HOME=/opt/apache-tomcat-10.1.16"
      become: true

    - name: Set Java Home environment variable
      lineinfile:
        path: "/etc/environment"
        line: "export JAVA_HOME={{ '/usr/lib/jvm/java-11-openjdk-amd64' if ansible_distribution == 'Ubuntu' else '/usr/lib/jvm/java-11' }}"
      become: true

    - name: Print JAVA_HOME
      debug:
        msg: "JAVA_HOME is set to {{ lookup('env', 'JAVA_HOME') }}"
      become: true

    - name: System CTL - Daemon reload
      ansible.builtin.command: "systemctl daemon-reload"
      become: true
      when: ansible_service_mgr == "systemd"

    - name: Debug output for systemd check
      ansible.builtin.debug:
        msg: "Systemd is {{ 'present' if 'systemd' in ansible_playbook_python | lower else 'not present' }}"

    - name: Start Tomcat service
      ansible.builtin.shell: |
         . /etc/environment
         export JAVA_HOME={{ '/usr/lib/jvm/java-11-openjdk-amd64' if ansible_distribution == 'Ubuntu' else '/usr/lib/jvm/java-11' }}
         nohup /opt/apache-tomcat-10.1.16/bin/startup.sh > /dev/null 2>&1 &
      when: "'systemd' not in ansible_playbook_python | lower"
      become: true

    - name: Print Tomcat status
      ansible.builtin.debug:
        msg: "{{ 'failed' if rc != 0 else 'succeeded' }}"
      when: rc != 0
...