---
- name: Manage Apache Tomcat
  hosts: group1
  become: true

  tasks:
    - name: Check if Apache Tomcat archive already exists
      stat:
        path: "/opt/apache-tomcat-8.5.72.tar.gz"
      register: tomcat_archive

    - name: Download Apache Tomcat 8.5.72 if not present
      get_url:
        url: "https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.72/bin/apache-tomcat-8.5.72.tar.gz"
        dest: "/opt/apache-tomcat-8.5.72.tar.gz"
      when: not tomcat_archive.stat.exists

    - name: Extract the Tomcat archive
      ansible.builtin.unarchive:
        src: "/opt/apache-tomcat-8.5.72.tar.gz"
        dest: "/opt/"
        remote_src: yes
      args:
        creates: /opt/apache-tomcat-8.5.72/  # Skip extraction if directory already present

    - name: Move Tomcat contents to /opt/tomcat
      command: "mv /opt/apache-tomcat-8.5.72/* /opt/tomcat/"
      args:
        creates: /opt/tomcat/bin/startup.sh  # Skip if files are already present

    - name: Set environment variables
      lineinfile:
        path: "/etc/environment"
        line: "CATALINA_HOME=/opt/tomcat"
        create: yes

    - name: System CTL
      command: "systemctl daemon-reload"

    - name: Shutdown Tomcat service
      command: "/opt/tomcat/bin/shutdown.sh"

    - name: Start Tomcat service
      command: "/opt/tomcat/bin/startup.sh"
...