---
- name: Update Package Managers, Install Tomcat, and Reload
  hosts: group1
  become: yes

  tasks:
    - name: Update package manager cache
      package_facts:
      run_once: yes

    - name: Install Tomcat on Ubuntu
      package:
        name: default-jdk, tomcat9  # Adjust the package names for Ubuntu
        state: present
      when: "'Ubuntu' in ansible_distribution"

    - name: Install Tomcat on Amazon Linux or CentOS
      yum:
        name: java, tomcat  # Adjust the package names for CentOS/Amazon Linux
        state: present
      when: "'Amazon' in ansible_distribution or 'CentOS' in ansible_distribution"

    - name: Reload Tomcat on Ubuntu
      systemd:
        name: tomcat9
        state: restarted
      when: "'Ubuntu' in ansible_distribution"
    
    - name: Reload Tomcat on Amazon Linux or CentOS
      systemd:
        name: tomcat  # Adjust the service name for Amazon Linux/CentOS
        state: restarted
      when: "'Amazon' in ansible_distribution or 'CentOS' in ansible_distribution"
...