---
- name: Install and Configure Tomcat 10 on Ubuntu, CentOS, and Amazon Linux
  hosts: group1
  become: yes

  tasks:
    - name: Update package system
      package:
        name: "*"
        state: latest
      when: "'Ubuntu' in ansible_distribution"

    - name: Update package system (CentOS)
      yum:
        name: "*"
        state: latest
      when: "'CentOS' in ansible_distribution"

    - name: Update package system (Amazon Linux)
      yum:
        name: "*"
        state: latest
      when: "'Amazon' in ansible_distribution"

    - name: Install default available Java
      package:
        name: default-jdk
        state: present
      when: "'Ubuntu' in ansible_distribution"

    - name: Install default available Java (CentOS)
      yum:
        name: java
        state: present
      when: "'CentOS' in ansible_distribution"

    - name: Install default available Java (Amazon Linux)
      yum:
        name: java
        state: present
      when: "'Amazon' in ansible_distribution"

    - name: Download and extract Apache Tomcat
      ansible.builtin.get_url:
        url: "https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.23/bin/apache-tomcat-10.0.23.tar.gz"
        dest: "/tmp/apache-tomcat-10.0.23.tar.gz"
      delegate_to: localhost

    - name: Extract Tomcat
      ansible.builtin.unarchive:
        src: "/tmp/apache-tomcat-10.0.23.tar.gz"
        dest: "/usr/local/"
        remote_src: yes
      become: yes

    - name: Move Tomcat directory
      command: "mv /usr/local/apache-tomcat-10.0.23 /usr/local/tomcat"
      become: yes

    - name: Start Tomcat
      command: "/usr/local/tomcat/bin/startup.sh"
      become: yes
      ignore_errors: yes

    - name: Display Java version
      command: "java -version"
      register: java_version_output
      ignore_errors: true

    - name: Display Tomcat version
      command: "/usr/local/tomcat/bin/version.sh"
      register: tomcat_version_output
      ignore_errors: true

    - name: Debug Information
      debug:
        var: item.stdout_lines
      loop:
        - "{{ java_version_output.stdout_lines }}"
        - "{{ tomcat_version_output.stdout_lines }}"
...