---
- hosts: group1
  vars:
    req_java: java-1.8.0-openjdk
    set_java: jre-1.8.0-openjdk
    tomcat_version: "10.1.16"
    tomcat_install_dir: "/usr/local"
  become: yes

  tasks:
    - name: Show existing Java versions and paths on CentOS
      ansible.builtin.shell:
        cmd: alternatives --display java
      when: "'CentOS' in ansible_distribution"
      register: java_info_centos

    - name: Debug CentOS Java information
      ansible.builtin.debug:
        var: java_info_centos.stdout_lines
      when: "'CentOS' in ansible_distribution"

    - name: Show existing Java versions and paths on Ubuntu
      ansible.builtin.shell:
        cmd: update-alternatives --display java
      when: "'Ubuntu' in ansible_distribution"
      register: java_info_ubuntu

    - name: Debug Ubuntu Java information
      ansible.builtin.debug:
        var: java_info_ubuntu.stdout_lines
      when: "'Ubuntu' in ansible_distribution"

    - name: Show existing Java versions and paths on Amazon Linux
      ansible.builtin.shell:
        cmd: alternatives --display java
      when: "'Amazon' in ansible_distribution"
      register: java_info_amazon

    - name: Debug Amazon Linux Java information
      ansible.builtin.debug:
        var: java_info_amazon.stdout_lines
      when: "'Amazon' in ansible_distribution"

    # The rest of the tasks remain unchanged...
    - name: Download Tomcat
      ansible.builtin.get_url:
        url: "https://dlcdn.apache.org/tomcat/tomcat-{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "{{ tomcat_install_dir }}"

    - name: Extract Tomcat
      ansible.builtin.unarchive:
        src: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "{{ tomcat_install_dir }}"
        remote_src: yes

    - name: Set Tomcat home
      ansible.builtin.command:
        cmd: mv "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}" "{{ tomcat_install_dir }}/latest"

    - name: Starting Tomcat
      ansible.builtin.shell:
        cmd: "nohup {{ tomcat_install_dir }}/latest/bin/startup.sh &"
...