---
- name: Install and configure tomcat
  hosts: group1
  gather_facts: true
  become: yes

  tasks:
    - name: Update repositories
      package:
        name: "*"
        state: latest
      loop:
        - "{{ 'dnf' if ansible_facts['distribution'] == 'Amazon' else 'yum' }}"
        - "{{ 'apt' if ansible_facts['distribution'] == 'Ubuntu' else '' }}"
      when: "'apt' in item or 'dnf' in item"

    - name: Install required java
      package:
        name: java-1.8.0-openjdk
        state: present
      loop:
        - "{{ 'dnf' if ansible_facts['distribution'] == 'Amazon' else 'yum' }}"
      when: "'yum' in item"

...