---
- name: Install Apache Tomcat 9.0.82 Deployer using Ansible
  hosts: group1
  become: true
  vars:
    tomcat_version: "9.0.82"
    tomcat_install_path: "/opt/tomcat{{ tomcat_version }}"
    tomcat_url: "https://dlcdn.apache.org/tomcat/tomcat-{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}-deployer.tar.gz"
    tomcat_service_file: "/etc/systemd/system/tomcat.service"

  tasks:
    - name: Update the System Packages on Ubuntu
      ansible.builtin.apt:
        upgrade: yes
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'

    - name: Install Update on Amazon Linux
      ansible.builtin.yum:
        name: update
      when: ansible_distribution == 'Amazon'

    - name: Install Update on Debian
      ansible.builtin.apt:
        upgrade: yes
        update_cache: yes
      when: ansible_distribution == 'Debian'

    - name: Install JAVA
      ansible.builtin.package:
        name: "{{ 'openjdk-11-jdk' if ansible_distribution in ['Debian', 'Ubuntu'] else 'java-11-amazon-corretto-headless' }}"
        state: present

    - name: Create a Tomcat User
      ansible.builtin.user:
        name: tomcat

    - name: Create a Tomcat Group
      ansible.builtin.group:
        name: tomcat

    - name: Create a Tomcat Directory
      ansible.builtin.file:
        path: "{{ tomcat_install_path }}"
        owner: tomcat
        group: tomcat
        mode: 755
        recurse: yes
        state: directory

    - name: Download Tomcat9 Deployer archive
      ansible.builtin.get_url:
        url: "{{ tomcat_url }}"
        dest: "/tmp/apache-tomcat-{{ tomcat_version }}-deployer.tar.gz"
        mode: '0755'

    - name: Unarchive Tomcat9 Deployer
      ansible.builtin.unarchive:
        src: "/tmp/apache-tomcat-{{ tomcat_version }}-deployer.tar.gz"
        dest: "{{ tomcat_install_path }}"
        remote_src: yes
        extra_opts: ['--strip-components=1']
        creates: "{{ tomcat_install_path }}/bin/catalina.sh"

    - name: Change ownership of Tomcat directory
      ansible.builtin.file:
        path: "{{ tomcat_install_path }}"
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory

    - name: Copy Tomcat service from local to remote
      ansible.builtin.copy:
        src: /local/path/to/tomcat.service
        dest: "{{ tomcat_service_file }}"
        mode: 0755
      when: ansible_distribution in ['Ubuntu', 'Amazon', 'Debian']

    - name: Start and Enable Tomcat on server
      ansible.builtin.systemd:
        name: tomcat
        state: started
        enabled: yes
        daemon_reload: yes
...