---
- name: Install Java and Apache Tomcat
  hosts: group1
  become: true
  gather_facts: true

  tasks:
    - name: Install Java 11
      ansible.builtin.include_role:
        name: geerlingguy.java
      vars:
        java_openjdk_packages:
          - "java-11-openjdk"

    - name: Display Java version
      ansible.builtin.command: java -version

    - name: Install wget
      ansible.builtin.package:
        name: wget
      when: "'Ubuntu' in ansible_distribution or 'CentOS' in ansible_distribution"

    - name: Create a directory for Java installation
      ansible.builtin.file:
        path: "/opt/java"
        state: directory

    - name: Set Java Home environment variable
      ansible.builtin.lineinfile:
        path: "/etc/environment"
        line: "export JAVA_HOME={{ '/usr/lib/jvm/java-11-openjdk-amd64' if 'Ubuntu' in ansible_distribution else '/usr/lib/jvm/java-11' if 'CentOS' in ansible_distribution else '/opt/java' }}"
      become: true

    - name: Download Apache Tomcat
      ansible.builtin.get_url:
        url: "https://downloads.apache.org/tomcat/tomcat-10/v10.1.16/bin/apache-tomcat-10.1.16.tar.gz"
        dest: "/tmp/apache-tomcat-10.1.16.tar.gz"

    - name: Extract Tomcat archive
      ansible.builtin.unarchive:
        src: "/tmp/apache-tomcat-10.1.16.tar.gz"
        dest: "/opt"
        remote_src: yes

    - name: Set Tomcat environment variables
      ansible.builtin.lineinfile:
        path: "/etc/environment"
        line: "export CATALINA_HOME=/opt/apache-tomcat-10.1.16"
      become: true

    - name: System CTL - Daemon reload
      ansible.builtin.command: "systemctl daemon-reload"
      become: true
      when: "'systemd' in ansible_service_mgr"

    - name: Debug output for systemd check
      ansible.builtin.debug:
        msg: "Systemd is {{ 'present' if 'systemd' in ansible_playbook_python | lower else 'not present' }}"

    - name: Start Tomcat service
      ansible.builtin.shell: >
        export JAVA_HOME={{ '/usr/lib/jvm/java-11-openjdk-amd64' if 'Ubuntu' in ansible_distribution else '/usr/lib/jvm/java-11' if 'CentOS' in ansible_distribution else '/opt/java' }};
        nohup /opt/apache-tomcat-10.1.16/bin/startup.sh > /dev/null 2>&1 &
      become: true
      when: "'systemd' not in ansible_playbook_python | lower"

    - name: Print Tomcat status
      ansible.builtin.shell: >
        export JAVA_HOME={{ '/usr/lib/jvm/java-11-openjdk-amd64' if 'Ubuntu' in ansible_distribution else '/usr/lib/jvm/java-11' if 'CentOS' in ansible_distribution else '/opt/java' }};
        /opt/apache-tomcat-10.1.16/bin/version.sh"
      register: tomcat_status

    - name: Print Tomcat status output
      ansible.builtin.debug:
        var: tomcat_status.stdout_lines
      when: tomcat_status.rc != 0
...