---
- name: Update Package Managers, Install Tomcat, and Reload
  hosts: all
  become: yes

  tasks:
    - name: Update package manager cache
      package_facts:
      run_once: yes

    - name: Install Tomcat
      package:
        name: "{{ item.pkg }}"
        state: present
      loop:
        - { pkg: 'tomcat', when: ansible_distribution == 'Ubuntu' }
        - { pkg: 'tomcat', when: ansible_distribution == 'Amazon' or ansible_distribution == 'CentOS' }

    - name: Reload Tomcat
      systemd:
        name: tomcat
        state: restarted
      when: "'Ubuntu' in ansible_distribution or 'Amazon' in ansible_distribution or 'CentOS' in ansible_distribution"
...