---
- hosts: group1
  become: true
  tasks:
    - name: Add Tomcat user
      user:
        name: tomcat
        home: /opt/tomcat
        shell: /bin/nologin
        createhome: false

    - name: Create Tomcat directory
      file:
        path: /opt/tomcat
        state: directory
        mode: 0750
        owner: tomcat
        group: tomcat

    - name: Download and extract Tomcat
      ansible.builtin.get_url:
        url: "https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.72/bin/apache-tomcat-8.5.72.tar.gz"
        dest: "/opt/tomcat/apache-tomcat.tar.gz"

    - name: Extract Tomcat archive
      ansible.builtin.unarchive:
        src: "/opt/tomcat/apache-tomcat.tar.gz"
        dest: "/opt/tomcat/"
        remote_src: true
        owner: tomcat
        group: tomcat

    - name: Start Tomcat service if it's inactive
      ansible.builtin.service:
        name: tomcat
        state: started
...