---
- hosts: group1
  become: true
  tasks:
    - name: Add Tomcat user
      ansible.builtin.user:
        name: tomcat
        home: /opt/tomcat
        shell: /bin/nologin
        createhome: false

    - name: Install Java 11
      ansible.builtin.package:
        name: "{{ java_package }}"
        state: present

    - name: Download and extract Tomcat
      ansible.builtin.get_url:
        url: "https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.72/bin/apache-tomcat-8.5.72.tar.gz"
        dest: /opt/tomcat/apache-tomcat.tar.gz

    - name: Create Tomcat directory
      ansible.builtin.unarchive:
        src: /opt/tomcat/apache-tomcat.tar.gz
        dest: /opt/tomcat
        remote_src: true
        owner: tomcat
        group: tomcat

    - name: Start and enable Tomcat
      ansible.builtin.systemd:
        name: tomcat
        enabled: yes
        state: started
    
...
