---
- name: Update Package Managers, Install Tomcat, and Reload
  hosts: group1
  become: yes

  tasks:
    - name: Gather Facts about the distribution
      setup:
      register: distribution_facts

    - name: Update package manager on Ubuntu
      apt:
        update_cache: yes
      when: "'Ubuntu' in distribution_facts.ansible_facts.distribution"

    - name: Update package manager on Amazon Linux
      yum:
        name: '*'
        state: latest
      when: "'Amazon' in distribution_facts.ansible_facts.distribution"

    - name: Update package manager on CentOS
      yum:
        name: '*'
        state: latest
      when: "'CentOS' in distribution_facts.ansible_facts.distribution"

    - name: Install Tomcat
      package:
        name: tomcat
        state: present
      when: "'Ubuntu' in distribution_facts.ansible_facts.distribution or 'Amazon' in distribution_facts.ansible_facts.distribution or 'CentOS' in distribution_facts.ansible_facts.distribution"

    - name: Reload Tomcat
      systemd:
        name: tomcat
        state: restarted
      when: "'Ubuntu' in distribution_facts.ansible_facts.distribution or 'Amazon' in distribution_facts.ansible_facts.distribution or 'CentOS' in distribution_facts.ansible_facts.distribution"
...