---
- name: Install and configure tomcat
  hosts: group1
  gather_facts: true
  become: yes

  tasks:
    - name: Update repositories
      package:
        name: "*"
        state: latest
      when:
        - ansible_facts['distribution'] == 'CentOS'
        - ansible_facts['distribution'] == 'Amazon'
        - ansible_facts['distribution'] == 'Ubuntu'

    - name: Set package manager variable
      set_fact:
        package_manager: "{{ 'dnf' if ansible_facts['distribution'] == 'Amazon' else 'yum' }}"
      when: ansible_facts['distribution'] in ['Amazon', 'CentOS']

    - name: Install required java on CentOS and Amazon
      package:
        name: java-1.8.0-openjdk
        state: present
      when: package_manager is defined
      loop:
        - "{{ package_manager }}"
      loop_control:
        label: "{{ item }}"

    - name: Install required java on Ubuntu
      package:
        name: openjdk-8-jre
        state: present
      when: ansible_facts['distribution'] == 'Ubuntu'
...