---
- name: Install Java and Apache Tomcat
  hosts: all
  become: true
  vars:
    java_package: "java-11-openjdk"
    tomcat_version: "10.1.16"
    tomcat_install_dir: "/opt/apache-tomcat-{{ tomcat_version }}"
    tomcat_url: "https://archive.apache.org/dist/tomcat/tomcat-10/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"

  tasks:
    - name: Update package cache on CentOS/RHEL
      package_facts:
        manager: auto

    - name: Install Java on CentOS/RHEL
      when: "'centos' in ansible_distribution or 'redhat' in ansible_distribution"
      package:
        name: "{{ java_package }}"
        state: present

    - name: Install Java on Ubuntu
      when: "'ubuntu' in ansible_distribution"
      apt:
        name: "{{ java_package }}"
        state: present

    - name: Download Apache Tomcat
      get_url:
        url: "{{ tomcat_url }}"
        dest: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"

    - name: Extract Tomcat archive
      ansible.builtin.unarchive:
        src: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "{{ tomcat_install_dir }}"
        remote_src: true

    - name: Set Tomcat environment variables
      lineinfile:
        dest: "/etc/environment"
        line: "CATALINA_HOME={{ tomcat_install_dir }}"
        state: present

    - name: Set JAVA_HOME on Ubuntu
      lineinfile:
        dest: "/etc/environment"
        line: "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64"
        state: present
      when: "'ubuntu' in ansible_distribution"

    - name: Set JAVA_HOME on CentOS/RHEL
      lineinfile:
        dest: "/etc/environment"
        line: "JAVA_HOME={{ ansible_env.JAVA_HOME }}"
        state: present
      when: "'centos' in ansible_distribution or 'redhat' in ansible_distribution"

    - name: Systemd - Daemon reload on CentOS/RHEL
      systemd:
        daemon_reload: yes
      when: "'centos' in ansible_distribution or 'redhat' in ansible_distribution"

    - name: Start Tomcat service
      command: "{{ tomcat_install_dir }}/bin/startup.sh"
...