---
- name: Install Apache Tomcat and Java
  hosts: group1
  become: true

  tasks:
    - name: Update package cache
      package:
        name: "*"
        state: latest
      when: ansible_distribution in ['RedHat', 'Amazon'] and ansible_python.version.major == 3

    - name: Install required packages
      package:
        name: "{{ item }}"
        state: present
      loop:
        - java-11-openjdk
      when: ansible_distribution == 'Amazon' or (ansible_distribution in ['RedHat', 'CentOS'] and ansible_python.version.major == 3)

    - name: Download Apache Tomcat
      get_url:
        url: "https://downloads.apache.org/tomcat/tomcat-10/v10.1.16/bin/apache-tomcat-10.1.16.tar.gz"
        dest: "/tmp/apache-tomcat-10.1.16.tar.gz"

    - name: Extract Tomcat archive
      ansible.builtin.unarchive:
        src: "/tmp/apache-tomcat-10.1.16.tar.gz"
        dest: "/opt"
        remote_src: yes

    - name: Set Tomcat environment variables
      lineinfile:
        path: "/etc/environment"
        line: "CATALINA_HOME=/opt/apache-tomcat-10.1.16"
      become: true

    - name: Set JAVA_HOME using set_fact
      ansible.builtin.set_fact:
        JAVA_HOME: "{{ ansible_java.java_home | default('/usr/lib/jvm/java-11-openjdk-amd64') }}"
      when: ansible_distribution == 'Amazon' or (ansible_distribution in ['RedHat', 'CentOS'] and ansible_python.version.major == 3)

    - name: Systemd - Daemon reload on CentOS/RHEL
      ansible.builtin.systemd:
        daemon_reload: yes
      become: yes
      when: ansible_distribution in ['Amazon', 'CentOS']

    - name: Debug output for systemd check
      ansible.builtin.debug:
        msg: "Systemd is {{ 'present' if 'systemd' in ansible_playbook_python | lower else 'not present' }}"

    - name: Start Tomcat service
      ansible.builtin.shell: "nohup /opt/apache-tomcat-10.1.16/bin/startup.sh"
      when: "'systemd' not in ansible_playbook_python | lower"
      become: true
...