---
- name: Install Apache Tomcat10 using ansible
  hosts: group1
  become: true
  tasks:
    - name: Update the System Packages
      ansible.builtin.package:
        name: update_cache
        cache_valid_time: 3600
      when: ansible_distribution == 'Ubuntu'

    - name: Install Update on Amazon Linux
      ansible.builtin.yum:
        name: update
      when: ansible_distribution == 'Amazon'

    - name: Update the System Packages on Debian
      ansible.builtin.apt:
        upgrade: yes
        update_cache: yes
      when: ansible_distribution == 'Debian'

    - name: Install JAVA
      ansible.builtin.package:
        name: default-jdk
        state: present

    - name: Create a Tomcat User
      ansible.builtin.user:
        name: tomcat

    - name: Create a Tomcat Group
      ansible.builtin.group:
        name: tomcat

    - name: Create a Tomcat Directory
      ansible.builtin.file:
        path: /opt/tomcat10
        owner: tomcat
        group: tomcat
        mode: 755
        recurse: yes
        state: directory

    - name: Download & Unarchive Tomcat10
      ansible.builtin.get_url:
        url: https://mirrors.estointernet.in/apache/tomcat/tomcat-10/v10.0.4/bin/apache-tomcat-10.0.4.tar.gz
        dest: /opt/tomcat10
        mode: '0755'
      ansible.builtin.unarchive:
        src: /opt/tomcat10/apache-tomcat-10.0.4.tar.gz
        dest: /opt/tomcat10
        remote_src: yes
        extra_opts: ['--strip-components=1']
        creates: /opt/tomcat10/bin/catalina.sh

    - name: Change ownership of Tomcat directory
      ansible.builtin.file:
        path: /opt/tomcat10
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory

    - name: Copy Tomcat service from local to remote
      ansible.builtin.copy:
        src: /etc/tomcat.service
        dest: /etc/systemd/system/
        mode: 0755

    - name: Start and Enable Tomcat 10 on server
      ansible.builtin.systemd:
        name: tomcat
        state: started
        enabled: yes
        daemon_reload: yes
...