---
- hosts: group1
  become: yes

  tasks:
    - name: Get service facts
      service_facts:

    - name: Print out service status
      debug:
        msg: “tomcat service status: {{ ansible_facts.services[‘tomcat.service’][‘state’] }}”

    - name: Set Java 11 as the active version on CentOS
      ansible.builtin.shell:
        cmd: update-alternatives --set java /usr/lib/jvm/java-11-openjdk-11.0.21.0.9-1.el7_9.x86_64/bin/java
      when: "'CentOS' in ansible_distribution"

    - name: Set Java 11 as the active version on Ubuntu
      ansible.builtin.shell:
        cmd: update-alternatives --set java /usr/lib/jvm/java-11-openjdk-amd64/bin/java
      when: "'Ubuntu' in ansible_distribution"

    - name: Set Java 11 as the active version on Amazon Linux
      ansible.builtin.shell:
        cmd: update-alternatives --set java /usr/lib/jvm/java-11-amazon-corretto.x86_64/bin/java
      when: "'Amazon' in ansible_distribution"

    - name: Download Tomcat
      ansible.builtin.get_url:
        url: "https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.16/bin/apache-tomcat-10.1.16.tar.gz"
        dest: "/usr/local"

    - name: Extract Tomcat
      ansible.builtin.unarchive:
        src: "/usr/local/apache-tomcat-10.1.16.tar.gz"
        dest: "/usr/local/bin"
        remote_src: yes

    - name: System CTL - Daemon reload
      ansible.builtin.command: "systemctl daemon-reload"
      become: yes
      when: "'Amazon' in ansible_distribution or 'CentOS' in ansible_distribution or 'Ubuntu' in ansible_distribution"

    - name: Starting Tomcat
      ansible.builtin.shell:
        cmd: "nohup /usr/local/latest/bin/startup.sh &"
...