---
- name: Install Apache Tomcat
  hosts: group1
  become: yes
  vars:
    tomcat_version: "8.5.72"
    tomcat_download_url: "https://archive.apache.org/dist/tomcat/tomcat-8/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
    tomcat_install_dir: "/opt/tomcat"

  tasks:
    - name: Update package cache
      package_facts:
        manager: auto

    - name: Install required packages
      package:
        name: "{{ item }}"
        state: present
      loop:
        - "{{ 'java-1.8.0-openjdk' if (ansible_distribution == 'Amazon' and ansible_distribution_major_version == '2') else 'openjdk-8-jre' }}"
        - "{{ 'libtcnative' if (ansible_distribution == 'Amazon' and ansible_distribution_major_version == '2') else 'libtcnative-1' }}"

    - name: Download Apache Tomcat archive
      get_url:
        url: "{{ tomcat_download_url }}"
        dest: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"

    - name: Extract Apache Tomcat archive
      ansible.builtin.unarchive:
        src: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "{{ tomcat_install_dir }}"
        remote_src: yes

    - name: Set ownership and permissions
      ansible.builtin.file:
        path: "{{ tomcat_install_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
        recurse: yes

    - name: Start Apache Tomcat
      ansible.builtin.shell:
        cmd: "{{ tomcat_install_dir }}/bin/startup.sh"
        executable: /bin/bash
      environment:
        CATALINA_HOME: "{{ tomcat_install_dir }}"
      async: 120
      poll: 0

    - name: Add Tomcat startup script to rc.local
      lineinfile:
        dest: /etc/rc.local
        line: "{{ tomcat_install_dir }}/bin/startup.sh"
        create: yes
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

    - name: Enable Tomcat service on Ubuntu
      systemd:
        name: tomcat
        enabled: yes
        state: started
      when: ansible_distribution == 'Ubuntu'
...