---
- name: Install Apache Tomcat 9.0.82 Deployer using Ansible
  hosts: group1
  become: true
  tasks:
    # ... (previous tasks)

    - name: Install Update on Amazon Linux
      ansible.builtin.dnf:
        name: update
      when: ansible_distribution == 'Amazon'

    - name: Install JAVA on Ubuntu
      ansible.builtin.package:
        name: openjdk-11-jre-headless
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Copy Tomcat service from local to remote
      ansible.builtin.copy:
        src: /local/path/to/tomcat.service
        dest: /etc/systemd/system/
        mode: 0755
      when: ansible_distribution in ['Ubuntu', 'Amazon', 'Debian']
...