---
- name: Install Apache Tomcat and Java
  hosts: group1
  become: true

  tasks:
    - name: Update package cache
      package:
        name: "*"
        state: latest
      when: ansible_distribution in ['RedHat', 'Amazon'] and ansible_python.version.major == 3

    - name: Install java-11-openjdk on CentOS/RHEL
      package:
        name: "java-11-openjdk"
        state: present
      when: ansible_distribution == 'RedHat' and ansible_pkg_mgr == 'yum'

    - name: Install java-11-openjdk on CentOS/RHEL (dnf)
      package:
        name: "java-11-openjdk"
        state: present
      when: ansible_distribution == 'RedHat' and ansible_pkg_mgr == 'dnf'

    - name: Install java-11-openjdk on Ubuntu
      package:
        name: "openjdk-11-jdk"
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Download Apache Tomcat
      get_url:
        url: "https://downloads.apache.org/tomcat/tomcat-10/v10.1.16/bin/apache-tomcat-10.1.16.tar.gz"
        dest: "/tmp/apache-tomcat-10.1.16.tar.gz"

    - name: Extract Tomcat archive
      ansible.builtin.unarchive:
        src: "/tmp/apache-tomcat-10.1.16.tar.gz"
        dest: "/opt"
        remote_src: yes

    - name: Set Tomcat environment variables
      lineinfile:
        path: "/etc/environment"
        line: "CATALINA_HOME=/opt/apache-tomcat-10.1.16"
      become: true

    - name: Set JAVA_HOME on Ubuntu
      lineinfile:
        path: "/etc/environment"
        line: "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64"
      when: ansible_distribution == 'Ubuntu'

    - name: Set JAVA_HOME on CentOS/RHEL
      lineinfile:
        path: "/etc/environment"
        line: "JAVA_HOME=/usr/lib/jvm/java-11"
      when: ansible_distribution == 'RedHat'

    - name: Systemd - Daemon reload on CentOS/RHEL
      ansible.builtin.systemd:
        daemon_reload: yes
      become: yes
      when: ansible_distribution in ['RedHat', 'CentOS', 'Ubuntu']

    - name: Debug output for systemd check
      ansible.builtin.debug:
        msg: "Systemd is {{ 'present' if 'systemd' in ansible_playbook_python | lower else 'not present' }}"

    - name: Start Tomcat service
      ansible.builtin.shell: "nohup /opt/apache-tomcat-10.1.16/bin/startup.sh"
      when: "'systemd' not in ansible_playbook_python | lower"
      become: true
...