---
- name: Install Apache Tomcat and Java
  hosts: group1
  become: true

  tasks:
    - name: Check the OS Distribution
      debug:
        var: ansible_distribution

    - name: Update package cache on Ubuntu
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Update package cache on CentOS
      yum:
        update_cache: yes
      when: ansible_distribution == "CentOS"

    - name: Install default available Java on Ubuntu
      apt:
        name: default-jdk
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Install OpenJDK on CentOS
      yum:
        name: java-11-openjdk
        state: present
      when: ansible_distribution == "CentOS"

    - name: Install wget
      package:
        name: wget
      when: ansible_distribution in ['Ubuntu', 'CentOS']

    - name: Create a directory for Tomcat installation
      file:
        path: /opt
        state: directory

    - name: Download Apache Tomcat
      ansible.builtin.get_url:
        url: "https://downloads.apache.org/tomcat/tomcat-10/v10.1.16/bin/apache-tomcat-10.1.16.tar.gz"
        dest: "/tmp/apache-tomcat-10.1.16.tar.gz"

    - name: Extract Tomcat archive
      ansible.builtin.unarchive:
        src: "/tmp/apache-tomcat-10.1.16.tar.gz"
        dest: "/opt"
        remote_src: yes

    - name: Set Tomcat environment variables
      lineinfile:
        path: "/etc/environment"
        line: "export CATALINA_HOME=/opt/apache-tomcat-10.1.16"
      become: true

    - name: Set Java Home environment variable dynamically
      lineinfile:
        path: "/etc/environment"
        line: "export JAVA_HOME={{ '/usr/lib/jvm/java-11-openjdk-amd64' if ansible_distribution == 'Ubuntu' else '/usr/lib/jvm/java-11' }}"
      become: true

    - name: System CTL - Daemon reload
      ansible.builtin.command: "systemctl daemon-reload"
      become: true
      when: ansible_service_mgr == "systemd"

    - name: Debug output for systemd check
      ansible.builtin.debug:
        msg: "Systemd is {{ 'present' if 'systemd' in ansible_playbook_python | lower else 'not present' }}"

    - name: Start Tomcat service
      ansible.builtin.shell: ". /etc/environment && export JAVA_HOME={{ '/usr/lib/jvm/java-11-openjdk-amd64' if ansible_distribution == 'Ubuntu' else '/usr/lib/jvm/java-11' }} && nohup /opt/apache-tomcat-10.1.16/bin/startup.sh"
      when: "'systemd' not in ansible_playbook_python | lower"
      become: true

    - name: Print Tomcat status
      ansible.builtin.debug:
        msg: "{{ ansible_run_status }}"
      when: "'failed' in ansible_run_status | lower"
...