<<<<<<< HEAD:04.tomcat.yml
=======

---
- hosts: group1
  become: true
  tasks:
    - name: Add Tomcat user
      ansible.builtin.user:
        name: tomcat
        home: /opt/tomcat
        shell: /bin/nologin
        createhome: false
>>>>>>> 7d80c5f0b4b5be1786a7f8abff834b6a61b90db7:05.tomcat.yml

