---
- name: Update Package Managers, Install Tomcat, and Reload
  hosts: all
  become: yes

  tasks:
    - name: Check distribution
      command: "{{ ansible_distribution }}"
      register: distribution_check

    - name: Update package manager on Ubuntu
      apt:
        update_cache: yes
      when: "'Ubuntu' in distribution_check.stdout"

    - name: Update package manager on Amazon Linux
      yum:
        name: '*'
        state: latest
      when: "'Amazon' in distribution_check.stdout"

    - name: Update package manager on CentOS
      yum:
        name: '*'
        state: latest
      when: "'CentOS' in distribution_check.stdout"

    - name: Install Tomcat on Ubuntu
      apt:
        name: tomcat
        state: present
      when: "'Ubuntu' in distribution_check.stdout"

    - name: Install Tomcat on Amazon Linux
      yum:
        name: tomcat
        state: present
      when: "'Amazon' in distribution_check.stdout"

    - name: Install Tomcat on CentOS
      yum:
        name: tomcat
        state: present
      when: "'CentOS' in distribution_check.stdout"

    - name: Reload Tomcat on Ubuntu
      service:
        name: tomcat
        state: reloaded
      when: "'Ubuntu' in distribution_check.stdout"

    - name: Reload Tomcat on Amazon Linux
      service:
        name: tomcat
        state: reloaded
      when: "'Amazon' in distribution_check.stdout"

    - name: Reload Tomcat on CentOS
      systemd:
        name: tomcat
        state: restarted
      when: "'CentOS' in distribution_check.stdout"
...