---
- name: Install and Configure Tomcat 10 on Multiple Operating Systems
  hosts: group1
  become: yes

  tasks:
    - name: Update package system (Ubuntu)
      apt:
        update_cache: yes
      when: "'Ubuntu' in ansible_distribution"

    - name: Update package system (CentOS)
      dnf:
        name: '*'
        state: latest
      when: "'CentOS' in ansible_os_family"

    - name: Install default available Java (Ubuntu)
      apt:
        name: default-jdk
        state: present
      when: "'Ubuntu' in ansible_distribution"

    - name: Install OpenJDK on CentOS
      dnf:
        name: java-1.8.0-openjdk
        state: present
      when: "'CentOS' in ansible_distribution"

    - name: Install wget
      package:
        name: wget
      when: "'Ubuntu' in ansible_distribution or 'CentOS' in ansible_os_family"

    - name: Create a directory for Tomcat installation
      file:
        path: /usr/local/tomcat
        state: directory

    - name: Download Tomcat 10
      ansible.builtin.get_url:
        url: "https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.16/bin/apache-tomcat-10.1.16.tar.gz"
        dest: "/usr/local/tomcat/apache-tomcat-10.1.16.tar.gz"

    - name: Extract Tomcat archive
      ansible.builtin.unarchive:
        src: "/usr/local/tomcat/apache-tomcat-10.1.16.tar.gz"
        dest: "/usr/local/tomcat/"
        remote_src: yes
      become: yes

    - name: System CTL Reload
      ansible.builtin.command: "systemctl daemon-reload"
      become: yes

    - name: Start Tomcat
      systemd:
        name: "tomcat"
        state: started
      become: yes
...