---
- name: Install and configure tomcat
  hosts: group1
  gather_facts: true
  become: yes

  tasks:
    - name: Update repositories
      package:
        name: "*"
        state: latest
      when:
        - ansible_facts['distribution'] == 'CentOS'
        - ansible_facts['distribution'] == 'Amazon'
        - ansible_facts['distribution'] == 'Ubuntu'

    - name: Install required java on CentOS and Amazon
      package:
        name: java-1.8.0-openjdk
        state: present
      when: ansible_facts['distribution'] in ['CentOS', 'Amazon']

    - name: Install required java on Ubuntu
      package:
        name: openjdk-8-jre
        state: present
      when: ansible_facts['distribution'] == 'Ubuntu'
...