---
- name: Install Apache Tomcat
  hosts: all
  become: yes
  tasks:
    - name: Install Java
      include_tasks: java_install.yml
      vars:
        java_home:
          Amazon: "/usr/lib/jvm/java-11-amazon-corretto.x86_64"
          Ubuntu: "/usr/lib/jvm/java-11-openjdk-amd64"
          CentOS: "/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.392.b08-2.el7_9.x86_64/jre"

    - name: Download Apache Tomcat
      get_url:
        url: "http://archive.apache.org/dist/tomcat/tomcat-9/v9.0.0.M1/bin/apache-tomcat-9.0.0.M1.tar.gz"
        dest: "/tmp/apache-tomcat.tar.gz"

    - name: Extract Apache Tomcat
      ansible.builtin.unarchive:
        src: "/tmp/apache-tomcat.tar.gz"
        dest: "/opt"
        remote_src: yes

    - name: Set Tomcat Environment Variables
      ansible.builtin.lineinfile:
        path: "/etc/environment"
        line: "CATALINA_HOME=/opt/apache-tomcat-9.0.0.M1"
        state: present

    - name: Start Tomcat Service
      ansible.builtin.service:
        name: tomcat
        state: started
...