---
- hosts: group1
  become: yes

  tasks:
    - name: Show active Java version on CentOS
      ansible.builtin.shell:
        cmd: alternatives --display java | grep 'currently points to'
      when: "'CentOS' in ansible_distribution"
      register: java_info_centos

    - name: Debug CentOS Java information
      ansible.builtin.debug:
        var: java_info_centos.stdout_lines
      when: "'CentOS' in ansible_distribution"

    - name: Show active Java version on Ubuntu
      ansible.builtin.shell:
        cmd: update-alternatives --display java | grep 'currently points to'
      when: "'Ubuntu' in ansible_distribution"
      register: java_info_ubuntu

    - name: Debug Ubuntu Java information
      ansible.builtin.debug:
        var: java_info_ubuntu.stdout_lines
      when: "'Ubuntu' in ansible_distribution"

    - name: Show active Java version on Amazon Linux
      ansible.builtin.shell:
        cmd: alternatives --display java | grep 'currently points to'
      when: "'Amazon' in ansible_distribution"
      register: java_info_amazon

    - name: Debug Amazon Linux Java information
      ansible.builtin.debug:
        var: java_info_amazon.stdout_lines
      when: "'Amazon' in ansible_distribution"

    - name: Download Tomcat
      ansible.builtin.get_url:
        url: "https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.16/bin/apache-tomcat-10.1.16.tar.gz"
        dest: "/usr/local"

    - name: Extract Tomcat
      ansible.builtin.unarchive:
        src: "/usr/local/apache-tomcat-10.1.16.tar.gz"
        dest: "/usr/local"
        remote_src: yes

    - name: Set Tomcat home
      ansible.builtin.command:
        cmd: mv "/usr/local/apache-tomcat-10.1.16" "/usr/local/latest"

    - name: Starting Tomcat
      ansible.builtin.shell:
        cmd: "nohup /usr/local/latest/bin/startup.sh &"
...