---
- name: Install and Configure Tomcat 10 on Multiple Operating Systems
  hosts: group1
  become: yes

  tasks:
    - name: Update package system
      package:
        name: '*'
        state: latest
      when: ansible_distribution in ['Ubuntu', 'CentOS']

    - name: Install default available Java on Ubuntu
      package:
        name: default-jdk
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Install OpenJDK on CentOS
      package:
        name: java-11-openjdk
        state: present
      when: ansible_distribution == 'CentOS'

    - name: Install wget
      package:
        name: wget
      when: ansible_distribution in ['Ubuntu', 'CentOS']

    - name: Create a directory for Tomcat installation
      file:
        path: /usr/local/tomcat
        state: directory

    - name: Download Tomcat 10
      ansible.builtin.get_url:
        url: "https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.16/bin/apache-tomcat-10.1.16.tar.gz"
        dest: "/usr/local/tomcat/apache-tomcat-10.1.16.tar.gz"

    - name: Extract Tomcat archive
      ansible.builtin.unarchive:
        src: "/usr/local/tomcat/apache-tomcat-10.1.16.tar.gz"
        dest: "/usr/local/tomcat/"
        remote_src: yes
      become: yes

    - name: Set Tomcat environment variables
      lineinfile:
        path: "/etc/environment"
        line: "CATALINA_HOME=/usr/local/tomcat/apache-tomcat-10.1.16"
      become: yes

    - name: Set Java Home environment variable dynamically
      lineinfile:
        path: "/etc/environment"
        line: "JAVA_HOME={{ '/usr/lib/jvm/java-11-openjdk-amd64' if ansible_distribution == 'Ubuntu' else '/usr/lib/jvm/java-11' }}"
      become: yes

    - name: System CTL - Daemon reload
      ansible.builtin.command: "systemctl daemon-reload"
      become: yes
      when: "'systemd' in ansible_playbook_python | lower and ansible_distribution in ['Amazon', 'CentOS']"

    - name: Debug output for systemd check
      ansible.builtin.debug:
        msg: "Systemd is {{ 'present' if 'systemd' in ansible_playbook_python | lower else 'not present' }}"

    - name: Start Tomcat service
      ansible.builtin.shell: "export JAVA_HOME=$(grep JAVA_HOME /etc/environment | cut -d'=' -f2) && nohup $JAVA_HOME/bin/java -jar /usr/local/tomcat/apache-tomcat-10.1.16/bin/startup.sh"
      when: "'systemd' not in ansible_playbook_python | lower"
      become: yes
...