---
- name: Install and configure Tomcat
  hosts: group1
  become: yes

  vars:
    tomcat_version: "10.1.15"
    tomcat_download_url: "https://dlcdn.apache.org/tomcat/tomcat-{{ tomcat_version }}/v{{ tomcat_version }}/src/apache-tomcat-{{ tomcat_version }}-src.tar.gz"

  tasks:
    - name: Ensure tomcat user is present
      user:
        name: tomcat
        system: yes
        shell: /bin/false

    - name: Set ownership of Tomcat directory
      file:
        path: /opt/tomcat
        state: directory
        owner: tomcat
        group: tomcat

    - name: Set ownership of Tomcat bin directory
      file:
        path: /opt/tomcat/bin
        state: directory
        owner: tomcat
        group: tomcat

    - name: Set execute permissions on startup script
      file:
        path: /opt/tomcat/bin/startup.sh
        state: file
        mode: '0755'

    - name: Download Tomcat
      get_url:
        url: "{{ tomcat_download_url }}"
        dest: "/opt/tomcat/apache-tomcat-{{ tomcat_version }}.tar.gz"
      register: download_result

    - name: Extract Tomcat
      ansible.builtin.unarchive:
        src: "/opt/tomcat/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "/opt/tomcat"
        remote_src: yes

    - name: Copy Tomcat systemd service file
      template:
        src: tomcat.service.j2
        dest: /etc/systemd/system/tomcat.service
      notify:
        - Reload systemd
        - Restart Tomcat

  handlers:
    - name: Reload systemd
      command: systemctl daemon-reload
      become: yes

    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted
...