---
- name: Install and configure Tomcat
  hosts: group1
  become: yes

  vars:
    tomcat_user: tomcat
    tomcat_group: tomcat
    tomcat_home: /opt/tomcat
    tomcat_bin: "{{ tomcat_home }}/bin/startup.sh"
    tomcat_service_src: /path/to/your/tomcat.service
    tomcat_service_dest: /etc/systemd/system/tomcat.service

  tasks:
    - name: Ensure tomcat user is present
      user:
        name: "{{ tomcat_user }}"
        system: yes
        shell: /bin/bash
        home: "{{ tomcat_home }}"

    - name: Set ownership of Tomcat directory
      file:
        path: "{{ tomcat_home }}"
        state: directory
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        recurse: yes

    - name: Set ownership of Tomcat bin directory
      file:
        path: "{{ tomcat_home }}/bin"
        state: directory
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        recurse: yes

    - name: Set execute permissions on startup script
      file:
        path: "{{ tomcat_bin }}"
        state: file
        mode: '0755'
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"

    - name: Copy Tomcat systemd service file
      copy:
        src: "{{ tomcat_service_src }}"
        dest: "{{ tomcat_service_dest }}"
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd after updating service file
      systemd:
        daemon_reload: yes

    - name: Start Tomcat service
      systemd:
        name: tomcat
        state: started
        enabled: yes
...