---
- name: Tomcat 10 installation
  hosts: group1
  become: true
  tasks:
    - name: Download tomcat 10 binaries
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.15/src/apache-tomcat-10.1.15-src.tar.gz
        dest: /opt
      register: download_result

    - name: Extract the binaries
      unarchive:
        src: "/opt/{{ download_result.url | basename }}"
        dest: /opt
        remote_src: yes

    - name: Rename the apache-tomcat-10.1.15-src directory
      command:
        cmd: mv "/opt/apache-tomcat-10.1.15-src" "/opt/tomcat"
      args:
        creates: /opt/tomcat  # Skip if directory is already renamed

    - name: Create tomcat group
      group:
        name: tomcat
        state: present
        system: yes

    - name: Create tomcat user
      user:
        name: tomcat
        group: tomcat
        password: pa$$w0rd  # Replace with a secure password
        home: /opt/tomcat
        shell: /bin/bash
        system: yes
      become: true

    - name: Change owner & group of tomcat directory
      file:
        path: /opt/tomcat
        owner: tomcat
        group: tomcat
        recurse: yes

    - name: Change owner & group of tomcat bin directory
      file:
        path: /opt/tomcat/bin
        owner: tomcat
        group: tomcat
        recurse: yes

    - name: Create empty Tomcat service file /etc/systemd/system/tomcat.service
      file:
        path: /etc/systemd/system/tomcat.service
        state: touch

    - name: Add tomcat service details in /etc/systemd/system/tomcat.service
      blockinfile:
        path: /etc/systemd/system/tomcat.service
        block: |
          [Unit]
          Description=Tomcat 10
          After=network.target
          
          [Service]
          Type=forking
          User=tomcat
          Group=tomcat
          Environment="JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64"
          Environment="JAVA_OPTS=-Djava.security.egd=file:///dev/urandom"
          Environment="CATALINA_BASE=/opt/tomcat"
          Environment="CATALINA_HOME=/opt/tomcat"
          Environment="CATALINA_PID=/opt/tomcat/temp/tomcat.pid"
          Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"
          ExecStart=/opt/tomcat/bin/startup.sh
          ExecStop=/opt/tomcat/bin/shutdown.sh
          
          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd daemon
      command: systemctl daemon-reload

    - name: Start tomcat Service
      service:
        name: tomcat
        state: started
        enabled: yes
...