---
- name: Install and configure Tomcat
  hosts: group1
  gather_facts: true
  become: yes

  tasks:
    - name: Update repositories
      package:
        name: "*"
        state: latest
      when: ansible_facts['distribution'] in ['CentOS', 'Amazon'] or ansible_facts['distribution'] == 'Ubuntu'

    - name: Install required Java on CentOS and Amazon
      package:
        name: java-1.8.0-openjdk
        state: present
      when: "'dnf' in ansible_playbook_python or 'yum' in ansible_playbook_python"
      loop:
        - "{{ 'dnf' if ansible_facts['distribution'] in ['Amazon', 'CentOS'] else 'yum' }}"
      loop_control:
        label: "{{ item }}"

    - name: Install required Java on Ubuntu
      package:
        name: openjdk-8-jre
        state: present
      when: "'apt' in ansible_playbook_python"
...