---
- name: Update Package Managers, Install Tomcat, and Reload
  hosts: group1
  become: yes

  tasks:
    - name: Update package manager cache
      package_facts:
      run_once: yes

    - name: Install Tomcat on Ubuntu
      package:
        name: tomcat
        state: present
      when: "'Ubuntu' in ansible_distribution"

    - name: Install Tomcat on Amazon Linux or CentOS
      package:
        name: tomcat
        state: present
      when: "'Amazon' in ansible_distribution or 'CentOS' in ansible_distribution"

    - name: Reload Tomcat on Ubuntu, Amazon Linux, or CentOS
      systemd:
        name: tomcat
        state: restarted
      when: "'Ubuntu' in ansible_distribution or 'Amazon' in ansible_distribution or 'CentOS' in ansible_distribution"
...