---
- hosts: group1
  become: true
  tasks:
    - name: Add Tomcat user
      user:
        name: tomcat
        home: /opt/tomcat
        shell: /bin/nologin
        createhome: false

    - name: Create Tomcat directory
      file:
        path: /opt/tomcat
        state: directory
        mode: 0750
        owner: tomcat
        group: tomcat

    - name: Download and extract Tomcat
      get_url:
        url: "https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.72/bin/apache-tomcat-8.5.72.tar.gz"
        dest: "/opt/tomcat/apache-tomcat.tar.gz"

    - name: Extract Tomcat archive
      ansible.builtin.unarchive:
        src: "/opt/tomcat/apache-tomcat.tar.gz"
        dest: "/opt/tomcat/"
        remote_src: true
        owner: tomcat
        group: tomcat

    - name: Reload and restart Tomcat service
      ansible.builtin.command:
        cmd: "systemctl daemon-reload && systemctl restart tomcat"
      ignore_errors: yes

    - name: Shutdown Tomcat service (fallback for non-systemd systems)
      ansible.builtin.command:
        cmd: "/opt/tomcat/bin/shutdown.sh"
      when: "'Active: active' in (ansible.builtin.command('systemctl status tomcat').stdout | default(''))"

    - name: Start Tomcat service (fallback for non-systemd systems)
      ansible.builtin.command:
        cmd: "/opt/tomcat/bin/startup.sh"
      when: "'Active: inactive' in (ansible.builtin.command('systemctl status tomcat').stdout | default(''))"
...