---
- name: Install and configure Tomcat
  hosts: group1
  become: yes

  tasks:
    - name: Ensure tomcat user is present
      user:
        name: tomcat
        system: yes
        shell: /bin/false

    - name: Set ownership of Tomcat directory
      file:
        path: /opt/tomcat
        state: directory
        owner: tomcat
        group: tomcat

    - name: Set ownership of Tomcat bin directory
      file:
        path: /opt/tomcat/bin
        state: directory
        owner: tomcat
        group: tomcat

    - name: Set execute permissions on startup script
      file:
        path: /opt/tomcat/bin/startup.sh
        state: file
        mode: '0755'

    - name: Download and extract Tomcat
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.15/src/apache-tomcat-10.1.15-src.tar.gz
        dest: /opt/tomcat/apache-tomcat.tar.gz

    - name: Extract Tomcat
      ansible.builtin.unarchive:
        src: /opt/tomcat/apache-tomcat.tar.gz
        dest: /opt/tomcat
        remote_src: yes

    - name: Copy Tomcat systemd service file
      template:
        src: tomcat.service.j2
        dest: /etc/systemd/system/tomcat.service
      notify: Reload systemd

  handlers:
    - name: Reload systemd
      command: systemctl daemon-reload
      become: yes

    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted

...