---
- name: Install and Configure Tomcat 10 on Ubuntu, CentOS, and Amazon Linux
  hosts: group1
  become: yes

  tasks:
    - name: Update package system
      apt:
        update_cache: yes
      when: "'Ubuntu' in ansible_distribution"

    - name: Update package system (CentOS)
      yum:
        name: '*'
        state: latest
      when: "'CentOS' in ansible_os_family"

    - name: Update package system (Amazon Linux)
      dnf:
        name: '*'
        state: latest
      when: "'Amazon' in ansible_os_family"

    - name: Install default available Java (Ubuntu)
      apt:
        name: default-jdk
        state: present
      when: "'Ubuntu' in ansible_distribution"

    - name: Install default available Java (CentOS)
      yum:
        name: java
        state: present
      when: "'CentOS' in ansible_distribution"

    - name: Install default available Java (Amazon Linux)
      dnf:
        name: java
        state: present
      when: "'Amazon' in ansible_distribution"

    - name: Check Java version
      command: "java -version"
      register: java_version_output
      ignore_errors: true

    - name: Display Java version
      debug:
        var: java_version_output.stdout_lines

    - name: Install wget
      apt:
        name: wget
        state: present
      when: "'Ubuntu' in ansible_distribution"

    - name: Install wget (CentOS)
      yum:
        name: wget
        state: present
      when: "'CentOS' in ansible_distribution"

    - name: Install wget (Amazon Linux)
      dnf:
        name: wget
        state: present
      when: "'Amazon' in ansible_distribution"

    - name: Create a directory for Tomcat installation
      file:
        path: /usr/local/tomcat
        state: directory

    - name: Download Tomcat 10
      ansible.builtin.get_url:
       url: "wget https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.23/bin/apache-tomcat-10.0.23.tar.gz"
       dest: "/usr/local/tomcat/apache-tomcat-10.0.23.tar.gz"

    - name: Extract Tomcat archive
      ansible.builtin.unarchive:
        src: "/usr/local/tomcat/apache-tomcat-10.0.23.tar.gz"
        dest: "/usr/local/tomcat/"
        remote_src: yes
      become: yes

    - name: Start Tomcat
      systemd:
        name: "tomcat"
        state: started
      when: "'Amazon' in ansible_os_family or 'CentOS' in ansible_os_family"

    - name: Start Tomcat (Ubuntu)
      systemd:
        name: "tomcat9"
        state: started
      when: "'Ubuntu' in ansible_os_family"
...