---
- name: Install and configure tomcat
  hosts: group1
  gather_facts: true
  become: yes

  tasks:
    - name: Debug distribution on CentOS
      debug:
        var: ansible_facts['distribution']
      when: "'CentOS' in ansible_facts['distribution']"

    - name: Debug distribution on Amazon
      debug:
        var: ansible_facts['distribution']
      when: "'Amazon' in ansible_facts['distribution']"

    - name: Debug distribution on Ubuntu
      debug:
        var: ansible_facts['distribution']
      when: "'Ubuntu' in ansible_facts['distribution']"

    - name: Update repositories
      package:
        name: "*"
        state: latest
      when:
        - ansible_facts['distribution'] == 'CentOS'
        - ansible_facts['distribution'] == 'Amazon'
        - ansible_facts['distribution'] == 'Ubuntu'

    - name: Install required java on CentOS and Amazon
      package:
        name: java-1.8.0-openjdk
        state: present
      when:
        - ansible_facts['distribution'] == 'CentOS'
        - ansible_facts['distribution'] == 'Amazon'

    - name: Install required java on Ubuntu
      package:
        name: openjdk-8-jre
        state: present
      when:
        - ansible_facts['distribution'] == 'Ubuntu'
...