---
- name: Install Java and Apache Tomcat
  hosts: group1
  become: true
  vars:
    java_package: "java-11-openjdk"
    tomcat_version: "10.1.16"
    tomcat_install_dir: "/opt/apache-tomcat-{{ tomcat_version }}"
    tomcat_url: "https://archive.apache.org/dist/tomcat/tomcat-10/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"

  tasks:
    - name: Debug - Print Distribution Information
      debug:
        var: ansible_distribution

    - name: Debug - Print Distribution Version
      debug:
        var: ansible_distribution_version

    - name: Update package cache
      package_facts:
        manager: auto

    - name: Install Java
      become: true
      block:
        - name: Install Java on CentOS/RHEL
          command: "{{ java_package }}"
          args:
            creates: "/usr/bin/java"
          when: "'centos' in ansible_distribution or 'redhat' in ansible_distribution"

        - name
...