---
- name: Install and Configure Tomcat on Multiple Operating Systems
  hosts: group1
  become: yes

  vars:
    tomcat_version: "10.0.23"
    tomcat_service_name: "tomcat"

  tasks:
    - name: Update package system
      package:
        name: "*"
        state: latest
      when: "'CentOS' in ansible_os_family or 'RedHat' in ansible_distribution_file_variety or 'Amazon' in ansible_distribution_file_variety"

    - name: Install default available Java
      package:
        name: java-1.8.0-openjdk
        state: present

    - name: Install wget
      package:
        name: wget
        state: present

    - name: Create a directory for Tomcat installation
      file:
        path: "/usr/local/tomcat"
        state: directory

    - name: Download Tomcat
      ansible.builtin.get_url:
        url: "https://archive.apache.org/dist/tomcat/tomcat-{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "/usr/local/tomcat/apache-tomcat-{{ tomcat_version }}.tar.gz"

    - name: Extract Tomcat archive
      ansible.builtin.unarchive:
        src: "/usr/local/tomcat/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "/usr/local/tomcat/"
        remote_src: yes
      become: yes

    - name: Reload systemd
      systemd:
        state: restarted
        name: "{{ tomcat_service_name }}"
      when: "'CentOS' in ansible_os_family or 'RedHat' in ansible_distribution_file_variety or 'Ubuntu' in ansible_os_family or 'Debian' in ansible_distribution_file_variety or 'Amazon' in ansible_distribution_file_variety"

    - name: Start Tomcat
      systemd:
        name: "{{ tomcat_service_name }}"
        state: started
      when: "'CentOS' in ansible_os_family or 'RedHat' in ansible_distribution_file_variety or 'Ubuntu' in ansible_os_family or 'Debian' in ansible_distribution_file_variety or 'Amazon' in ansible_distribution_file_variety"
...