---
- name: Update Package Managers, Install Tomcat, and Reload
  hosts: group1
  become: yes

  tasks:
    - name: Update package manager cache
      package_facts:
      run_once: yes

    - name: Install Tomcat on Ubuntu
      package:
        name: default-jdk, tomcat9  # Adjust the package names for Ubuntu
        state: present
      when: "'Ubuntu' in ansible_distribution"

    - name: Install Tomcat on Amazon Linux or CentOS
      # Use 'yum' for Amazon Linux
      yum:
        name: java, tomcat  # Adjust the package names for Amazon Linux
        state: present
      when: "'Amazon' in ansible_distribution or 'CentOS' in ansible_distribution"

    - name: Reload Tomcat on Ubuntu, Amazon Linux, or CentOS
      systemd:
        name: tomcat9  # Adjust the service name for Ubuntu
        state: restarted
      when: "'Ubuntu' in ansible_distribution or 'Amazon' in ansible_distribution or 'CentOS' in ansible_distribution"
...