---
- hosts: group1
  vars:
    req_java: java-1.8.0-openjdk
    set_java: jre-1.8.0-openjdk
  become: yes
  
  tasks:
    - name: Set default java
      alternatives:
        name: java
        link: /usr/bin/java
        path: /usr/lib/jvm/set_java/bin/java

    - name: Download Tomcat
      get_url:
        url: "https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.16/bin/apache-tomcat-10.1.16.tar.gz"
        dest: /usr/local

    - name: Extract Tomcat
      unarchive:
        src: "/usr/local/apache-tomcat-10.1.16.tar.gz"
        dest: /usr/local
        remote_src: yes

    - name: Set Tomcat home
      command: mv /usr/local/apache-tomcat-10.1.16 /usr/local/latest

    - name: Starting tomcat
      shell:  nohup /usr/locall/latest/bin/startup.sh &
...