---
- name: Install Java and Apache Tomcat
  hosts: group1
  become: true
  gather_facts: true

  tasks:
    - name: Install Java 11 on CentOS
      ansible.builtin.yum:
        name: java-11-openjdk
        state: present
      when: "'CentOS' in ansible_distribution"

    - name: Install Java 11 on Ubuntu
      ansible.builtin.apt:
        name: openjdk-11-jdk
        state: present
      when: "'Ubuntu' in ansible_distribution"

    - name: Set Java Home environment variable
      ansible.builtin.lineinfile:
        path: "/etc/environment"
        line: "export JAVA_HOME={{ '/usr/lib/jvm/java-11-openjdk-amd64' if 'Ubuntu' in ansible_distribution else '/usr/lib/jvm/java-11' if 'CentOS' in ansible_distribution else '/opt/java' }}"
      become: true

    - name: Download Apache Tomcat
      ansible.builtin.get_url:
        url: "https://downloads.apache.org/tomcat/tomcat-10/v10.1.16/bin/apache-tomcat-10.1.16.tar.gz"
        dest: "/tmp/apache-tomcat-10.1.16.tar.gz"

    - name: Extract Tomcat archive
      ansible.builtin.unarchive:
        src: "/tmp/apache-tomcat-10.1.16.tar.gz"
        dest: "/opt"
        remote_src: yes

    - name: Set Tomcat environment variables
      ansible.builtin.lineinfile:
        path: "/etc/environment"
        line: "export CATALINA_HOME=/opt/apache-tomcat-10.1.16"
      become: true

    - name: System CTL - Daemon reload
      ansible.builtin.command: "systemctl daemon-reload"
      become: true
      when: "'systemd' in ansible_service_mgr | lower"

    - name: Debug output for systemd check
      ansible.builtin.debug:
        msg: "Systemd is {{ 'present' if 'systemd' in ansible_playbook_python | lower else 'not present' }}"

    - name: Start Tomcat service
      ansible.builtin.shell: |
         . /etc/environment
         export JAVA_HOME={{ '/usr/lib/jvm/java-11-openjdk-amd64' if 'Ubuntu' in ansible_distribution else '/usr/lib/jvm/java-11' if 'CentOS' in ansible_distribution else '/opt/java' }}
         nohup /opt/apache-tomcat-10.1.16/bin/startup.sh > /dev/null 2>&1 &
      when: "'systemd' not in ansible_playbook_python | lower"
      become: true

    - name: Print Tomcat status
      ansible.builtin.shell: "source /etc/environment && /opt/apache-tomcat-10.1.16/bin/version.sh"
      ignore_errors: true
...