---
- name: Copy files from build server to tomcat servers
  hosts: n4c
  become: true
  tasks:
    - name: Copy files to other servers
      synchronize:
        src: "/home/centos/ansibleproject/target/*.war"
        dest:  "/usr/local/bin/apache-tomcat-10.1.16/webapps/"
      delegate_to: "{{ item }}"
      with_items: "{{ groups['group1'] }}"
...
