---
- name: Deploy Artifacts into Tomcat on Nodes in group1
  hosts: group1
  become: true

  tasks:
    - name: Remove existing *.war files from webapps folder
      ansible.builtin.shell:
        cmd: "find /usr/local/bin/apache-tomcat-10.1.16/webapps/ -name '*.war' -type f -delete"
      ignore_errors: yes

    - name: Find .war files on build server (n4c)
      ansible.builtin.shell:
        cmd: "find /home/centos/ansibleproject/target/ -name '*.war' -type f"
      register: warfile
      delegate_to: n4c  # delegate the task to Ansible Controller

    - name: Save warfile list to a file
      ansible.builtin.copy:
        content: "{{ warfile.stdout_lines | join('\n') }}"
        dest: "/tmp/warfile_list.txt"

- name: Copy .war files from n4c to Ansible Controller
  hosts: n4c
  become: true

  tasks:
    - name: Fetch warfile list from Ansible Controller
      ansible.builtin.fetch:
        src: "/tmp/warfile_list.txt"
        dest: "/tmp/"
        flat: yes

- name: Deploy Artifacts into Tomcat on Nodes in group1
  hosts: group1
  become: true

  tasks:
    - name: Copy .war files to target hosts
      ansible.builtin.copy:
        src: "/tmp/{{ item }}"
        dest: "/usr/local/bin/apache-tomcat-10.1.16/webapps/"
        remote_src: yes
      loop: "{{ lookup('file', '/tmp/warfile_list.txt').splitlines() }}"
      loop_control:
        loop_var: item
...
