---
- name: Update Package Managers, Install Tomcat, and Reload
  hosts: group1
  become: yes

  tasks:
    - name: Gather Facts about the distribution
      setup:
      register: distribution_facts

    - name: Update package manager cache
      package_facts:
      run_once: yes

    - name: Install Tomcat
      package:
        name: "{{ item.pkg }}"
        state: present
      loop:
        - { pkg: 'tomcat', when: ansible_distribution == 'Ubuntu' }
        - { pkg: 'tomcat', when: ansible_distribution == 'Amazon' or ansible_distribution == 'CentOS' }

    - name: Reload Tomcat
      systemd:
        name: tomcat
        state: restarted
      when: "'Ubuntu' in distribution_facts.ansible_facts.distribution or 'Amazon' in distribution_facts.ansible_facts.distribution or 'CentOS' in distribution_facts.ansible_facts.distribution"
...