---
- hosts: n4u
  gather_facts: false
  tasks:
    - name: Get remote directory
      command: "pwd"
      register: remote_directory
      become: true

    - name: Get Java home
      command: "echo $JAVA_HOME"
      register: java_home
      become: true

    - name: Get Maven home
      command: "echo $M2_HOME"
      register: maven_home
      become: true

    - name: Display information
      debug:
        msg: |
          Remote Directory: {{ remote_directory.stdout_lines }}
          Java Home: {{ java_home.stdout_lines }}
          Maven Home: {{ maven_home.stdout_lines }}
...