---
- hosts: n4u
  gather_facts: false
  tasks:
    - name: Get remote directory
      command: "pwd"
      register: remote_directory
      become: true

    - name: Display remote directory
      debug:
        var: remote_directory.stdout_lines
    
    - name: Get Maven home directory
      command: "dirname $(dirname $(which mvn))"
      register: maven_directory
      become: true

    - name: Display Maven home directory
      debug:
        var: maven_directory.stdout_lines

    - name: Get Java home directory
      command: "dirname $(dirname $(which java))"
      register: java_directory
      become: true

    - name: Display Java home directory
      debug:
        var: java_directory.stdout_lines
...