---
- name: Display Root, Java, and Maven information
  hosts: n4u
  become: true
  gather_facts: true
  tasks:
    - name: Display Root, Java, and Maven information
      ansible.builtin.debug:
        msg: |
          root_directory: {{ ansible_mounts[0].mount }}
          java_home: {{ ansible_env.JAVA_HOME }}
          maven_home: {{ ansible_env.MAVEN_HOME }}
...