---
- hosts: n4u
  gather_facts: false
  tasks:
    - name: Get remote directory
      command: "pwd"
      register: remote_directory
      become: true

    - name: Display remote directory
      debug:
        var: remote_directory.stdout_lines
...