---
- name: Check Tomcat and Java Versions
  hosts: all
  gather_facts: true
  tasks:
    - name: Check Tomcat Version
      shell: |
        catalina.sh version | grep "Server version"
      register: tomcat_version
      changed_when: false
      ignore_errors: yes
      when: "'RedHat' in ansible_os_family or 'Amazon' in ansible_os_family"

    - name: Check Tomcat Version on Ubuntu
      shell: |
        /etc/init.d/tomcat9 version | grep "Server version"
      register: tomcat_version
      changed_when: false
      ignore_errors: yes
      when: "'Debian' in ansible_os_family"

    - name: Display Tomcat Version
      debug:
        var: tomcat_version.stdout_lines
      when: tomcat_version.rc == 0

    - name: Check Java Version
      command: java -version
      register: java_version
      changed_when: false
      ignore_errors: yes

    - name: Display Java Version
      debug:
        var: java_version.stdout_lines
      when: java_version.rc == 0
...