---
- name: Check Tomcat and Java Versions
  hosts: all
  gather_facts: true
  tasks:
    - name: Check Tomcat Version (CentOS)
      command: catalina.sh version
      register: tomcat_version
      ignore_errors: yes
      when: "'RedHat' in ansible_os_family or 'Amazon' in ansible_os_family"

    - name: Check Tomcat Version on Ubuntu
      command: /etc/init.d/tomcat9 version
      register: tomcat_version
      ignore_errors: yes
      when: "'Debian' in ansible_os_family"

    - name: Display Tomcat Version
      debug:
        var: tomcat_version.stderr_lines
      when: tomcat_version|failed

    - name: Check Java Version
      command: java -version
      register: java_version
      ignore_errors: yes

    - name: Display Java Version
      debug:
        var: java_version.stderr_lines
      when: java_version|failed
...