---
- name: Install Jenkins, Ansible, and set Java 11 as the active version on CentOS
  hosts: n4c
  become: true

  tasks:
    - name: Add Jenkins repository
      yum_repository:
        name: jenkins
        description: Jenkins Official Repository
        baseurl: http://pkg.jenkins.io/redhat-stable
        gpgcheck: true
        gpgkey: http://pkg.jenkins.io/redhat-stable/jenkins.io.key
        state: present

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Install EPEL repository
      yum:
        name: epel-release
        state: present

    - name: Install Ansible
      yum:
        name: ansible
        state: present

    - name: Install Java 11
      yum:
        name: java-11-openjdk
        state: present

    - name: Set Java 11 as the default version
      alternatives:
        name: java
        path: /usr/lib/jvm/java-11-openjdk-11/bin/java
        priority: 2

    - name: Display Java version
      command: java -version
      register: java_version_output

    - name: Display Java path
      debug:
        var: java_version_output.stdout_lines
        msg: "Java Path: {{ java_version_output.stdout_lines | join('\n') }}"

    - name: Start Jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: true
...