---
- name: Install Jenkins on CentOS/RHEL
  hosts: n4u
  become: true
  tasks:
    - name: Install Wget
      ansible.builtin.yum:
        name: wget
        state: present

    - name: Import Jenkins GPG key
      ansible.builtin.shell:
        cmd: "sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key"

    - name: Add Jenkins repository
      ansible.builtin.shell:
        cmd: "sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo"

    - name: Upgrade packages
      ansible.builtin.yum:
        name: '*'
        state: latest

    - name: Install Jenkins
      ansible.builtin.yum:
        name: jenkins
        state: present

    - name: Reload systemd manager configuration
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable and start Jenkins service
      ansible.builtin.systemd:
        name: jenkins
        enabled: yes
        state: started
...