- name: Install Jenkins
  hosts: n4u
  become: true
  tasks:
    - name: Install Jenkins on CentOS
      ansible.builtin.yum:
        name: jenkins
        state: present
        enablerepo: epel
      when: "'CentOS' in ansible_distribution"

    - name: Install Jenkins on Amazon Linux
      ansible.builtin.dnf:
        name: jenkins
        state: present
      when: "'Amazon' in ansible_distribution"

    - name: Install Jenkins on Ubuntu
      ansible.builtin.apt:
        name: jenkins
        state: present
      when: "'Ubuntu' in ansible_distribution"

    - name: Display Jenkins Version
      ansible.builtin.shell:
        cmd: "java -jar /usr/share/jenkins/jenkins.war --version"
      register: jenkins_version

    - name: Display Jenkins Version Info
      ansible.builtin.debug:
        var: jenkins_version.stdout_lines
...