- name: Install Jenkins and Ansible on Ubuntu
  hosts: n4u
  become: true
  tasks:
    - name: Debug APT Cache Update (Before)
      ansible.builtin.debug:
        var: ansible_pkg_mgr_update_cache_update_cache.stdout
      when: "'Ubuntu' in ansible_distribution"

    - name: Update package repositories
      ansible.builtin.apt:
        update_cache: yes
      register: apt_update_result
      when: "'Ubuntu' in ansible_distribution"

    - name: Debug APT Update Result
      ansible.builtin.debug:
        var: apt_update_result
      when: "'Ubuntu' in ansible_distribution"

    - name: Debug APT Package List
      ansible.builtin.debug:
        var: apt_update_result.package_list
      when: "'Ubuntu' in ansible_distribution"

    # ... (the rest of your tasks)

    - name: Display Jenkins Initial Admin Password
      ansible.builtin.shell:
        cmd: sudo cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_initial_password

    - name: Display Jenkins Initial Admin Password Info
      ansible.builtin.debug:
        var: jenkins_initial_password.stdout_lines
...