---
- name: Install Jenkins, Ansible, and set Java 11 as the active version on CentOS
  hosts: n4c
  become: true

  tasks:
    - name: Add Jenkins repository
      yum_repository:
        name: jenkins
        description: Jenkins Official Repository
        baseurl: http://pkg.jenkins.io/redhat-stable
        gpgcheck: false
        state: present

    - name: Import Jenkins GPG key
      rpm_key:
        key: http://pkg.jenkins.io/redhat-stable/jenkins.io.key
        state: present

    - name: Enable GPG check for Jenkins repository
      ini_file:
        path: /etc/yum.repos.d/jenkins.repo
        section: jenkins
        option: gpgcheck
        value: 1
        backup: yes
      notify:
        - Run Yum Clean

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Install EPEL repository
      yum:
        name: epel-release
        state: present

    - name: Install Ansible
      yum:
        name: ansible
        state: present

    - name: Install Java 11
      yum:
        name: java-11-openjdk
        state: present

    - name: Set Java 11 as the default version
      alternatives:
        name: java
        path: /usr/lib/jvm/java-11-openjdk-11.0.21.0.9-1.el7_9.x86_64/bin/java
        priority: 2

    - name: Start Jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: true

  handlers:
    - name: Run Yum Clean
      command: yum clean all
...