---
- name: Install Jenkins on CentOS/RHEL
  hosts: n4c
  become: true
  tasks:
    - name: Install Wget
      ansible.builtin.yum:
        name: wget
        state: present

    - name: Import Jenkins GPG key
      ansible.builtin.yum_key:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
        state: present

    - name: Upgrade packages
      ansible.builtin.yum:
        name: '*'
        state: latest

    - name: Install Jenkins
      ansible.builtin.yum:
        name: jenkins
        state: present

    - name: Reload systemd manager configuration
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable and start Jenkins service
      ansible.builtin.systemd:
        name: jenkins
        enabled: yes
        state: started
...