- name: Install Jenkins on Ubuntu
  hosts: n4u
  become: true
  tasks:
    - name: Install Wget
      ansible.builtin.apt:
        name: wget
        state: present

    - name: Add Jenkins GPG key
      ansible.builtin.apt_key:
        url: "https://pkg.jenkins.io/debian/jenkins.io.key"

    - name: Add Jenkins repository
      ansible.builtin.apt_repository:
        repo: "deb http://pkg.jenkins.io/debian-stable binary/"

    - name: Upgrade packages
      ansible.builtin.apt:
        upgrade: yes
        update_cache: yes

    - name: Install Jenkins
      ansible.builtin.apt:
        name: jenkins
        state: present

    - name: Display Jenkins Initial Admin Password
      ansible.builtin.shell:
        cmd: sudo cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_initial_password

    - name: Display Jenkins Initial Admin Password Info
      ansible.builtin.debug:
        var: jenkins_initial_password.stdout_lines
...