- name: Install Jenkins and Ansible on Ubuntu
  hosts: n4u
  become: true
  tasks:
    - name: Debug APT Cache Update (Before)
      ansible.builtin.debug:
        var: ansible_pkg_mgr_update_cache_update_cache.stdout
      when: "'Ubuntu' in ansible_distribution"

    - name: Update package repositories
      ansible.builtin.apt:
        update_cache: yes
      register: apt_update
      when: "'Ubuntu' in ansible_distribution"

    - name: Debug APT Cache Update (After)
      ansible.builtin.debug:
        var: apt_update.stdout
      when: "'Ubuntu' in ansible_distribution"

    - name: Debug APT Package List
      ansible.builtin.debug:
        var: apt_update.package_list
      when: "'Ubuntu' in ansible_distribution"

    - name: Add Jenkins GPG key
      ansible.builtin.apt_key:
        url: "https://pkg.jenkins.io/debian/jenkins.io.key"
      when: "'Ubuntu' in ansible_distribution"

    - name: Debug Jenkins Repository Contents
      ansible.builtin.debug:
        var: ansible_apt.list
      when: "'Ubuntu' in ansible_distribution"

    - name: Install Jenkins on Ubuntu
      ansible.builtin.apt:
        name: jenkins
        state: present
      when: "'Ubuntu' in ansible_distribution"

    - name: Install Ansible on Ubuntu
      ansible.builtin.apt:
        name: ansible
        state: present
      when: "'Ubuntu' in ansible_distribution"

    - name: Set Java 11 as the active version on Ubuntu
      ansible.builtin.shell:
        cmd: update-alternatives --set java /usr/lib/jvm/java-11-openjdk-amd64/bin/java
      when: "'Ubuntu' in ansible_distribution"

    - name: Display Jenkins Initial Admin Password
      ansible.builtin.shell:
        cmd: sudo cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_initial_password

    - name: Display Jenkins Initial Admin Password Info
      ansible.builtin.debug:
        var: jenkins_initial_password.stdout_lines
...