---
- name: Install Jenkins and Ansible on Ubuntu
  hosts: n4u
  become: true
  tasks:
    - name: Update package repositories
      ansible.builtin.apt:
        update_cache: yes
      when: "'Ubuntu' in ansible_distribution"

    - name: Add Jenkins GPG key
      ansible.builtin.apt_key:
        url: "https://pkg.jenkins.io/debian/jenkins.io.key"
      when: "'Ubuntu' in ansible_distribution"

    - name: Add Jenkins repository
      ansible.builtin.apt_repository:
        repo: "deb http://pkg.jenkins.io/debian-stable binary/"
      when: "'Ubuntu' in ansible_distribution"

    - name: Install Jenkins on Ubuntu
      ansible.builtin.apt:
        name: jenkins
        state: present
      when: "'Ubuntu' in ansible_distribution"

    - name: Install Ansible on Ubuntu
      ansible.builtin.apt:
        name: ansible
        state: present
      when: "'Ubuntu' in ansible_distribution"

    - name: Set Java 11 as the active version on Ubuntu
      ansible.builtin.shell:
        cmd: update-alternatives --set java /usr/lib/jvm/java-11-openjdk-amd64/bin/java
      when: "'Ubuntu' in ansible_distribution"

    - name: Display Jenkins Initial Admin Password
      ansible.builtin.shell:
        cmd: sudo cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_initial_password

    - name: Display Jenkins Initial Admin Password Info
      ansible.builtin.debug:
        var: jenkins_initial_password.stdout_lines

    - name: Display Root, Java, and Maven information
      ansible.builtin.debug:
        msg: |
          root_directory: {{ root_directory }}
          java_home: {{ java_home }}
          maven_home: {{ maven_home }}
...