---
- name: Install Ansible
  hosts: n1a
  become: true
  tasks:
    - name: Debug distribution major version information
      ansible.builtin.debug:
        var: ansible_distribution_major_version

    - name: Debug Ansible availability in dnf repo
      ansible.builtin.debug:
        var: "ansible_package_available"
      when: "'CentOS' in ansible_distribution"

    - name: Download and Install EPEL repository on CentOS
      ansible.builtin.get_url:
        url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
        dest: "/tmp/epel-release-latest.rpm"
      when: "'CentOS' in ansible_distribution"

    - name: Install EPEL repository on CentOS
      ansible.builtin.command:
        cmd: "dnf install -y /tmp/epel-release-latest.rpm"
      when: "'CentOS' in ansible_distribution"
...
