---
- name: Update dnf and install prerequisites
  hosts: n1a
  become: true
  tasks:
    - name: Update dnf
      ansible.builtin.command:
        cmd: "dnf makecache"

    - name: Install Python 3
      ansible.builtin.dnf:
        name: python3
        state: present

    - name: Install Pip for Python 3
      ansible.builtin.dnf:
        name: python3-pip
        state: present

- name: Install Ansible using Pip
  hosts: n1a
  become: true
  tasks:
    - name: Install Ansible using Pip
      ansible.builtin.command:
        cmd: "/usr/bin/pip3 install ansible"
...