---
- name: Install EPEL repository and Ansible
  hosts: all
  become: true
  tasks:
    - name: Install EPEL repository on CentOS
      ansible.builtin.command:
        cmd: "dnf install -y epel-release"
      when: "'CentOS' in ansible_distribution"

    - name: Install EPEL repository on Amazon Linux
      ansible.builtin.command:
        cmd: "amazon-linux-extras install epel -y"
      when: "'Amazon' in ansible_distribution"

    - name: Install Ansible on CentOS and Amazon Linux
      ansible.builtin.command:
        cmd: "dnf install -y ansible"
      when: "'CentOS' in ansible_distribution or 'Amazon' in ansible_distribution"

    - name: Install Ansible on Ubuntu
      ansible.builtin.apt:
        name: ansible
        state: present
      when: "'Ubuntu' in ansible_distribution"

    - name: Debug Ansible installation status
      ansible.builtin.debug:
        var: "ansible_is_installed"
...