---
- name: Install Ansible
  hosts: group1
  become: true
  tasks:
    - name: Install software-properties-common on Ubuntu
      ansible.builtin.apt:
        name: software-properties-common
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Add Ansible repository on Ubuntu
      ansible.builtin.apt_repository:
        repo: 'ppa:ansible/ansible'
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Install Ansible on Ubuntu
      ansible.builtin.package:
        name: ansible
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Install EPEL repository on CentOS
      ansible.builtin.yum:
        name: epel-release
        state: present
      when: ansible_distribution == 'CentOS'

    - name: Install Ansible on CentOS
      ansible.builtin.yum:
        name: ansible
        state: present
      when: ansible_distribution == 'CentOS'

    - name: Install EPEL repository on Amazon Linux
      ansible.builtin.dnf:
        name: epel-release
        state: present
      when: ansible_distribution == 'Amazon'
    - name: Install Ansible on Amazon Linux
      ansible.builtin.dnf:
        name: ansible
        state: present
      when: ansible_distribution == 'Amazon'
...