---
- name: Install EPEL repository and Ansible
  hosts: n1a
  become: true
  tasks:
    - name: Debug PATH
      ansible.builtin.debug:
        var: ansible_env.PATH

    - name: Install EPEL repository on CentOS
      ansible.builtin.yum:
        name: epel-release
        state: present
      when: "'CentOS' in ansible_distribution"

    - name: Install EPEL repository on Amazon Linux
      ansible.builtin.command:
        cmd: "/usr/bin/amazon-linux-extras install epel -y"
        warn: false
      when: "'Amazon' in ansible_distribution and '/usr/bin/amazon-linux-extras' is file"

    - name: Install Ansible on CentOS and Amazon Linux
      ansible.builtin.package:
        name: ansible
        state: present
      when: "'CentOS' in ansible_distribution or 'Amazon' in ansible_distribution"

    - name: Install Ansible on Ubuntu
      ansible.builtin.apt:
        name: ansible
        state: present
      when: "'Ubuntu' in ansible_distribution"

    - name: Debug Ansible installation status
      ansible.builtin.debug:
        var: "ansible_is_installed"
...