---
- name: Install Ansible on CentOS
  hosts: n4c
  become: true
  tasks:
    - name: Install EPEL repository
      ansible.builtin.yum:
        name: epel-release
        state: present

    - name: Install Ansible
      ansible.builtin.yum:
        name: ansible
        state: present
...