---
- name: Install EPEL repository and Ansible
  hosts: all
  become: true
  tasks:
    - name: Install EPEL repository on CentOS and Amazon Linux
      ansible.builtin.yum:
        name: epel-release
        state: present
      when: "'CentOS' in ansible_distribution or 'Amazon' in ansible_distribution"

    - name: Install Ansible on CentOS and Amazon Linux
      ansible.builtin.yum:
        name: ansible
        state: present
      when: "'CentOS' in ansible_distribution or 'Amazon' in ansible_distribution"

    - name: Install Ansible on Ubuntu
      ansible.builtin.apt:
        name: ansible
        state: present
      when: "'Ubuntu' in ansible_distribution"

    - name: Debug Ansible installation status
      ansible.builtin.debug:
        var: "ansible_is_installed"
...