---
- name: Apache Maven Environmental Variables
  hosts: n4u
  become: yes

  tasks:
    - name: Update Maven environment variables in /etc/profile.d/maven.sh
      lineinfile:
        path: /etc/profile.d/maven.sh
        regexp: "^(export JAVA_HOME=).*"
        line: "export JAVA_HOME=/usr/lib/jvm/jre-openjdk"

    - name: Append Maven environment variables to /etc/profile.d/maven.sh
      blockinfile:
        path: /etc/profile.d/maven.sh
        block: |
          export M2_HOME=/opt/maven
          export MAVEN_HOME=/opt/maven
          export PATH=${M2_HOME}/bin:${PATH}
...