---
- name: Deploy WAR file to Tomcat
  hosts: group1
  become: yes

  vars:
    tomcat_version: "apache-tomcat-10.1.16"
    tomcat_home: "/usr/local/bin/{{ tomcat_version }}"

  tasks:
    - name: Set execute permissions for Tomcat scripts
      ansible.builtin.file:
        path: "{{ tomcat_home }}/bin/*.sh"
        mode: 'u+x,g+x'
        recurse: yes

    - name: System CTL - Daemon reload
      ansible.builtin.command: "systemctl daemon-reload"
      when: "'Amazon' in ansible_distribution or 'CentOS' in ansible_distribution or 'Ubuntu' in ansible_distribution"

    - name: Starting Tomcat
      ansible.builtin.shell:
        cmd: "nohup /usr/local/bin/apache-tomcat-10.1.16/bin/startup.sh &"
...
