- name: Download Tomcat
  ansible.builtin.get_url:
    url: "https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.16/bin/apache-tomcat-10.1.16.tar.gz"
    dest: "/usr/local"

- name: Extract Tomcat
  ansible.builtin.unarchive:
    src: "/usr/local/apache-tomcat-10.1.16.tar.gz"
    dest: "/usr/local/bin"
    remote_src: yes

- name: Set execute permissions for Tomcat scripts
  ansible.builtin.file:
    path: "/usr/local/bin/apache-tomcat-10.1.16/bin/*.sh"
    mode: 'u+x,g+x'
    recurse: yes

- name: Install Tomcat init script
  ansible.builtin.copy:
    src: "/usr/local/bin/apache-tomcat-10.1.16/bin/catalina.sh"
    dest: "/etc/init.d/tomcat"
    mode: '0755'
    remote_src: yes

- name: Start Tomcat
  ansible.builtin.service:
    name: tomcat
    state: started
    enabled: yes

- name: Print out service status if Tomcat service is present
  ansible.builtin.debug:
    msg: "Tomcat service status: {{ ansible_facts.services['tomcat']['state'] | default('Service not found') }}"
  when: "'tomcat' in ansible_facts.services"
