- name: Gather Facts
  ansible.builtin.setup:

- name: Download Tomcat
  ansible.builtin.get_url:
    url: "https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.16/bin/apache-tomcat-10.1.16.tar.gz"
    dest: "/usr/local"

- name: Extract Tomcat
  ansible.builtin.unarchive:
    src: "/usr/local/apache-tomcat-10.1.16.tar.gz"
    dest: "/usr/local/bin"
    remote_src: yes

- name: Install Tomcat init script
  ansible.builtin.copy:
    src: "/usr/local/bin/apache-tomcat-10.1.16/bin/catalina.sh"
    dest: "/etc/init.d/tomcat"
    mode: '0755'
    remote_src: yes
