- name: Starting Tomcat
  ansible.builtin.command:
    cmd: "{{ catalina_home }}/bin/startup.sh"
  environment:
    CATALINA_HOME: "{{ catalina_home }}"

- name: Print out service status if Tomcat service is present
  ansible.builtin.debug:
    msg: "Tomcat service status: {{ ansible_facts.services['tomcat.service']['state'] | default('Service not found') }}"
  when: 
    - "'services' in ansible_facts"
    - "'tomcat.service' in ansible_facts.services"
    - "'running' in ansible_facts.services['tomcat.service']['state']"
