    - name: Reload systemd
      become: yes
      systemd:
        daemon-reload: yes

  handlers:
    - name: Restart Tomcat
      become: yes
      systemd:
        name: tomcat
        state: restarted