- name: Get Java home directory
  command: "{{ 'dirname $(dirname $(readlink -f $(which java)))' }}"
  register: java_home
  ignore_errors: true

- name: Set Java home fact
  set_fact:
    java_home: "{{ java_home.stdout | regex_replace('\n', '') }}"
  when: java_home.rc == 0
