
- name: Get Java home directory on {{ target_host }}
  command: "dirname $(dirname $(readlink -f $(which java)))"
  register: java_directory
  become: true

- name: Display Java home directory on {{ target_host }}
  debug:
    var: java_directory.stdout_lines