---
# tasks file for jenkins
    - name: Install Wget
      ansible.builtin.yum:
        name: wget
        state: present

    - name: Download Jenkins GPG key
      ansible.builtin.get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
        dest: /etc/pki/rpm-gpg/jenkins.io.key

    - name: Import Jenkins GPG key
      ansible.builtin.shell:
        cmd: "rpm --import /etc/pki/rpm-gpg/jenkins.io.key"

    - name: Add Jenkins repository with GPG check disabled
      ansible.builtin.shell:
        cmd: "echo -e '[jenkins]\nname=Jenkins\nbaseurl=http://pkg.jenkins.io/redhat-stable\nenabled=1\ngpgcheck=0' > /etc/yum.repos.d/jenkins.repo"

    - name: Upgrade packages
      ansible.builtin.yum:
        name: '*'
        state: latest

    - name: Install Jenkins
      ansible.builtin.yum:
        name: jenkins
        state: present

    - name: Reload systemd manager configuration
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable and start Jenkins service
      ansible.builtin.systemd:
        name: jenkins
        enabled: yes
        state: started

    - name: Display Jenkins Initial Admin Password
      ansible.builtin.shell:
        cmd: "sudo cat /var/lib/jenkins/secrets/initialAdminPassword"
      register: jenkins_initial_password

    - name: Display Jenkins Initial Admin Password Info
      ansible.builtin.debug:
        var: jenkins_initial_password.stdout_lines