---
- name: Get Maven home directory on {{ target_host }}
  command: "dirname $(dirname $(readlink -f $(which mvn)))"
  register: maven_directory
  become: true

- name: Display Maven home directory on {{ target_host }}
  debug:
    var: maven_directory.stdout_lines