- name: Get Maven home directory
  command: "dirname $(dirname $(readlink -f $(which mvn)))"
  register: maven_directory
  become: true

- name: Display Maven home directory
  debug:
    var: maven_directory.stdout_lines
